// Generated by scripts/build-runtime.mjs. Do not edit.
// source: capability-client/source/fetch.js
(() => {
  function abortReason(signal) {
    return signal.reason === undefined
      ? new DOMException("This operation was aborted", "AbortError")
      : signal.reason;
  }

  function awaitOperation(operation, signal) {
    if (!signal) return operation.promise;
    if (signal.aborted) {
      tysel._cancelOp(operation.id);
      return Promise.reject(abortReason(signal));
    }
    return new Promise((resolve, reject) => {
      let settled = false;
      let aborted = false;
      const onAbort = () => {
        if (settled) return;
        aborted = true;
        tysel._cancelOp(operation.id);
      };
      signal.addEventListener("abort", onAbort, { once: true });
      operation.promise.then(
        (value) => {
          if (settled) return;
          settled = true;
          signal.removeEventListener("abort", onAbort);
          if (aborted || signal.aborted) reject(abortReason(signal));
          else resolve(value);
        },
        (error) => {
          if (settled) return;
          settled = true;
          signal.removeEventListener("abort", onAbort);
          reject(signal.aborted ? abortReason(signal) : error);
        },
      );
    });
  }

  globalThis.__tysel_awaitOperation = awaitOperation;

  globalThis.fetch = async function(input, init) {
    init = init || {};
    const signal = init.signal || (input && input.signal) || null;
    if (signal && signal.aborted) throw abortReason(signal);
    const url = typeof input === "string" ? input : input.url;
    const method = String(init.method || (input && input.method) || "GET").toUpperCase();
    const headers = new Headers(init.headers || (input && input.headers));
    const pairs = [];
    headers.forEach((value, key) => pairs.push([key, value]));
    let body = "";
    if (init.body != null) body = String(init.body);
    else if (input instanceof Request && (input._stream || input.body != null)) body = await input.text();
    else if (input && typeof input !== "string" && input.body != null) body = String(input.body);
    const operation = tysel._httpStart(String(url), method, JSON.stringify(pairs), body);
    const started = await awaitOperation(operation, signal);
    let headerPairs = [];
    try { headerPairs = JSON.parse(started.headers || "[]"); } catch (_) {}
    const response = new Response(null, { status: started.status, headers: headerPairs });
    response._stream = true;
    response._signal = signal;
    response._bodyId = started.bodyId;
    if (signal) {
      const cancelBody = () => tysel._httpCancelBody(response._bodyId);
      signal.addEventListener("abort", cancelBody, { once: true });
      response._abortCleanup = () => signal.removeEventListener("abort", cancelBody);
    }
    return response;
  };
  globalThis.tysel.httpGet = function(url) {
    return fetch(url);
  };
})();

// source: capability-client/source/accepted-websocket.js
(() => {
  class AcceptedWebSocket extends EventTarget {
    constructor() {
      super();
      this.readyState = 1;
      this.onmessage = null;
      this.onclose = null;
      this.onerror = null;
    }
    send(data) {
      return tysel._wsSend(data == null ? "" : String(data));
    }
    close() {
      this.readyState = 2;
      return tysel._wsClose();
    }
    _dispatch(type, init) {
      const event = globalThis.__tysel_event(type, init);
      this.dispatchEvent(event);
    }
  }
  globalThis.tysel.acceptWebSocket = function() {
    if (globalThis.__tysel_ws_accepted) {
      throw new Error("websocket already accepted");
    }
    globalThis.__tysel_ws_accepted = true;
    const socket = new AcceptedWebSocket();
    globalThis.__tysel_ws_done = (async () => {
      let close = { code: 1000, reason: "", wasClean: true };
      try {
        for (;;) {
          const chunk = await tysel._wsRead();
          if (chunk == null) break;
          socket._dispatch("message", { data: chunk });
        }
      } catch (error) {
        close = { code: 1006, reason: String(error), wasClean: false };
        socket._dispatch("error", { error });
      } finally {
        socket.readyState = 3;
        socket._dispatch("close", close);
      }
    })();
    return socket;
  };
})();

// source: capability-client/source/websocket.js
(() => {
  if (!Number.isInteger(globalThis.__tysel_request_generation)) {
    globalThis.__tysel_request_generation = 0;
  }
  class WebSocket extends EventTarget {
    static CONNECTING = 0;
    static OPEN = 1;
    static CLOSING = 2;
    static CLOSED = 3;
    constructor(url) {
      super();
      this.url = String(url);
      this._generation = globalThis.__tysel_request_generation;
      this.readyState = WebSocket.CONNECTING;
      this.binaryType = "arraybuffer";
      this.onopen = null;
      this.onmessage = null;
      this.onerror = null;
      this.onclose = null;
      this.opened = tysel._wsConnect(this.url).then(() => {
        if (this._generation !== globalThis.__tysel_request_generation) return this;
        this.readyState = WebSocket.OPEN;
        this._dispatch("open", { type: "open", target: this });
        this._readLoop();
        return this;
      }, (error) => {
        if (this._generation !== globalThis.__tysel_request_generation) return this;
        this.readyState = WebSocket.CLOSED;
        this._dispatch("error", { type: "error", error, target: this });
        this._dispatch("close", { type: "close", code: 1006, reason: String(error), wasClean: false, target: this });
        throw error;
      });
    }
    send(data) {
      if (this.readyState !== WebSocket.OPEN) throw new DOMException("WebSocket is not open", "InvalidStateError");
      return tysel._wsClientSend(data == null ? "" : String(data));
    }
    async close() {
      if (this.readyState === WebSocket.CLOSED || this.readyState === WebSocket.CLOSING) return;
      this.readyState = WebSocket.CLOSING;
      await tysel._wsClientClose();
    }
    _dispatch(type, init) {
      if (this._generation !== globalThis.__tysel_request_generation) return;
      const event = globalThis.__tysel_event(type, init);
      this.dispatchEvent(event);
    }
    async _readLoop() {
      try {
        while (this.readyState === WebSocket.OPEN) {
          const frame = await tysel._wsClientRead();
          if (this._generation !== globalThis.__tysel_request_generation) return;
          if (frame.type === "close") {
            this.readyState = WebSocket.CLOSED;
            this._dispatch("close", {
              type: "close",
              code: frame.code,
              reason: frame.reason,
              wasClean: frame.wasClean,
              target: this,
            });
            return;
          }
          let data = frame.data;
          if (Array.isArray(data)) data = Uint8Array.from(data).buffer;
          this._dispatch("message", { type: "message", data, target: this });
        }
        this.readyState = WebSocket.CLOSED;
        this._dispatch("close", { type: "close", code: 1000, reason: "", wasClean: true, target: this });
      } catch (error) {
        if (this._generation !== globalThis.__tysel_request_generation) return;
        this.readyState = WebSocket.CLOSED;
        this._dispatch("error", { type: "error", error, target: this });
        this._dispatch("close", { type: "close", code: 1006, reason: String(error), wasClean: false, target: this });
      }
    }
  }
  for (const name of ["CONNECTING", "OPEN", "CLOSING", "CLOSED"]) {
    Object.defineProperty(WebSocket.prototype, name, { value: WebSocket[name] });
  }
  globalThis.WebSocket = WebSocket;
})();

// source: capability-client/source/storage.js
(() => {
  globalThis.tysel.sqlite = {
    exec(sql, params) {
      return tysel._sqliteExec(String(sql), JSON.stringify(params == null ? [] : params));
    },
    query(sql, params) {
      return tysel._sqliteQuery(String(sql), JSON.stringify(params == null ? [] : params));
    },
  };
  globalThis.tysel.postgres = {
    exec(sql, params) {
      return tysel._pgExec(String(sql), JSON.stringify(params == null ? [] : params));
    },
    query(sql, params) {
      return tysel._pgQuery(String(sql), JSON.stringify(params == null ? [] : params));
    },
  };
  globalThis.tysel.fs = {
    read(path) {
      return tysel._fsRead(String(path));
    },
    write(path, data) {
      return tysel._fsWrite(String(path), data == null ? "" : String(data));
    },
  };
  globalThis.tysel.secrets = {
    ref(name) {
      return tysel._secretRef(String(name));
    },
  };
})();

// source: capability-client/source/llm.js
(() => {
  globalThis.tysel.llm = {
    generate(options) {
      if (options === null || typeof options !== "object" || Array.isArray(options)) {
        throw new TypeError("llm.generate options must be an object");
      }
      return tysel._llmGenerate(JSON.stringify(options));
    },
  };
})();
