[package]
name = "tysel-cap-fs"
version.workspace = true
publish = false
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true
description = "Official filesystem capability."

[lints]
workspace = true

[target.'cfg(unix)'.dependencies]
libc.workspace = true
