// Generated by `wit-bindgen` 0.59.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     tysel:component@0.4.0

package main

import (
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"runtime"
	"unsafe"
	"wit_component/export_wit_world"
)

var staticPinner = runtime.Pinner{}
var exportReturnArea = uintptr(witRuntime.Allocate(&staticPinner, (3 * 4), 4))
var syncExportPinner = runtime.Pinner{}

//go:wasmexport run
func wasm_export_wit_world_run(arg0 uintptr, arg1 uint32) uintptr {

	pinner := &syncExportPinner
	value := unsafe.String((*uint8)(unsafe.Pointer(arg0)), arg1)
	witRuntime.Unpin()
	result := export_wit_world.Run(value)

	switch result.Tag() {
	case witTypes.ResultOk:
		payload := result.Ok()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(0))
		utf8 := unsafe.Pointer(unsafe.StringData(payload))
		pinner.Pin(utf8)
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (2 * 4))) = uint32(uint32(len(payload)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = uint32(uintptr(uintptr(utf8)))

	case witTypes.ResultErr:
		payload := result.Err()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(1))
		utf80 := unsafe.Pointer(unsafe.StringData(payload))
		pinner.Pin(utf80)
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (2 * 4))) = uint32(uint32(len(payload)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = uint32(uintptr(uintptr(utf80)))

	default:
		panic("unreachable")
	}
	return exportReturnArea

}

//go:wasmexport cabi_post_run
func wasm_export_post_return_wit_world_run(result uintptr) {
	syncExportPinner.Unpin()
}

// Unused, but present to make the compiler happy
func main() {}
