import { readFileSync, writeFileSync } from "node:fs";
import { dirname, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const args = process.argv.slice(2);
const unexpected = args.filter((arg) => arg !== "--check");
if (unexpected.length > 0) {
  throw new Error(`unknown build argument: ${unexpected.join(", ")}`);
}
const checkOnly = args.includes("--check");

const targets = [
  {
    output: "web-api/runtime.js",
    sources: [
      "web-api/source/event.js",
      "web-api/source/url.js",
      "web-api/source/utilities.js",
      "web-api/vendor/web-streams-polyfill/polyfill.js",
      "web-api/source/http.js",
      "web-api/source/encoding.js",
      "web-api/source/timers.js",
      "web-api/source/abort.js",
      "web-api/source/crypto.js",
    ],
  },
  {
    output: "capability-client/runtime.js",
    sources: [
      "capability-client/source/fetch.js",
      "capability-client/source/accepted-websocket.js",
      "capability-client/source/websocket.js",
      "capability-client/source/storage.js",
      "capability-client/source/llm.js",
    ],
  },
  {
    output: "durable/runtime.js",
    prefix: "(() => {\n",
    suffix: "})();\n",
    sources: ["durable/source/helpers.part.js", "durable/source/api.part.js"],
  },
];

function readSource(path) {
  const source = readFileSync(resolve(root, path), "utf8").replaceAll("\r\n", "\n").trimEnd();
  if (path === "web-api/vendor/web-streams-polyfill/polyfill.js") {
    const license = readFileSync(resolve(root, "web-api/vendor/web-streams-polyfill/LICENSE"), "utf8").trimEnd();
    const globals = [
      "ReadableStream", "ReadableStreamDefaultController", "ReadableByteStreamController",
      "ReadableStreamBYOBRequest", "ReadableStreamDefaultReader", "ReadableStreamBYOBReader",
      "WritableStream", "WritableStreamDefaultController", "WritableStreamDefaultWriter",
      "ByteLengthQueuingStrategy", "CountQueuingStrategy", "TransformStream", "TransformStreamDefaultController",
    ];
    return `/*\n${license}\n*/\n(() => {
  let constructors;
  let slots = [];
  function load() {
    if (constructors) return;
    // Evaluate against a private global facade: vendor installation must never
    // overwrite an application's replacements or fail on sealed globals.
    constructors = tysel._loadStreams();
    for (const [name, get, set] of slots) {
      const descriptor = Object.getOwnPropertyDescriptor(globalThis, name);
      if (descriptor && descriptor.configurable && descriptor.get === get && descriptor.set === set) {
        Object.defineProperty(globalThis, name, {
          value: constructors[name], writable: true, configurable: true,
        });
      }
    }
    slots = null;
  }
  // Buffered bodies must not trigger loading merely to test instanceof.
  globalThis.__tysel_isReadableStream = value => constructors !== undefined && value instanceof constructors.ReadableStream;
  for (const name of ${JSON.stringify(globals)}) {
    const get = () => { load(); return constructors[name]; };
    const set = value => {
      load();
      Object.defineProperty(globalThis, name, {value, writable: true, configurable: true});
    };
    slots.push([name, get, set]);
    Object.defineProperty(globalThis, name, {configurable: true, get, set});
  }
})();`;
  }
  return source;
}

function build(target) {
  const sections = target.sources.map(
    (source) => `// source: ${source}\n${readSource(source)}`,
  );
  return [
    "// Generated by scripts/build-runtime.mjs. Do not edit.",
    target.prefix || "",
    sections.join("\n\n"),
    target.suffix || "",
  ]
    .filter(Boolean)
    .join("\n")
    .replaceAll("\r\n", "\n")
    .trimEnd()
    .concat("\n");
}

const stale = [];
for (const target of targets) {
  const outputPath = resolve(root, target.output);
  const generated = build(target);
  if (checkOnly) {
    let current = "";
    try {
      current = readFileSync(outputPath, "utf8");
    } catch {
      // A missing output is stale and will be reported below.
    }
    if (current !== generated) stale.push(relative(root, outputPath));
  } else {
    writeFileSync(outputPath, generated);
  }
}

if (stale.length > 0) {
  process.stderr.write(
    `generated runtime artifacts are stale: ${stale.join(", ")}\n` +
      "run: pnpm --filter @tysel/runtime-js build:runtime\n",
  );
  process.exitCode = 1;
}
