// Generated by scripts/build-runtime.mjs. Do not edit.
// source: web-api/source/event.js
(() => {
  const eventStates = new WeakMap();
  const targetStates = new WeakMap();

  function isListener(listener) {
    return typeof listener === "function" ||
      (listener != null && typeof listener.handleEvent === "function");
  }

  function callListener(listener, target, event) {
    try {
      if (typeof listener === "function") listener.call(target, event);
      else listener.handleEvent(event);
    } catch {
      // Listener failures do not propagate through dispatchEvent and cannot
      // terminate native I/O pumps.
    }
  }

  function captureOption(options) {
    return typeof options === "boolean" ? options : Boolean(options && options.capture);
  }

  class Event {
    constructor(type, init) {
      if (arguments.length === 0) throw new TypeError("Event type is required");
      init = init || {};
      eventStates.set(this, {
        target: null,
        currentTarget: null,
        dispatching: false,
        stopped: false,
        immediate: false,
        canceled: false,
      });
      Object.defineProperties(this, {
        type: { value: String(type), enumerable: true },
        bubbles: { value: Boolean(init.bubbles), enumerable: true },
        cancelable: { value: Boolean(init.cancelable), enumerable: true },
        composed: { value: Boolean(init.composed), enumerable: true },
        timeStamp: { value: Date.now(), enumerable: true },
      });
    }
    get target() { return eventStates.get(this).target; }
    get currentTarget() { return eventStates.get(this).currentTarget; }
    get defaultPrevented() { return eventStates.get(this).canceled; }
    stopPropagation() { eventStates.get(this).stopped = true; }
    stopImmediatePropagation() {
      const state = eventStates.get(this);
      state.stopped = true;
      state.immediate = true;
    }
    preventDefault() {
      if (this.cancelable) eventStates.get(this).canceled = true;
    }
  }

  class EventTarget {
    constructor() {
      targetStates.set(this, []);
    }
    addEventListener(type, listener, options) {
      if (!isListener(listener)) return;
      type = String(type);
      const capture = captureOption(options);
      const entries = targetStates.get(this);
      if (entries.some((entry) =>
        entry.type === type && entry.listener === listener && entry.capture === capture
      )) return;
      const entry = {
        type,
        listener,
        capture,
        once: Boolean(options && typeof options === "object" && options.once),
      };
      entries.push(entry);
      const signal = options && typeof options === "object" ? options.signal : null;
      if (signal) {
        if (signal.aborted) this.removeEventListener(type, listener, capture);
        else signal.addEventListener("abort", () => this.removeEventListener(type, listener, capture), { once: true });
      }
    }
    removeEventListener(type, listener, options) {
      const capture = captureOption(options);
      const entries = targetStates.get(this);
      type = String(type);
      targetStates.set(this, entries.filter((entry) =>
        entry.type !== type || entry.listener !== listener || entry.capture !== capture
      ));
    }
    dispatchEvent(event) {
      if (!(event instanceof Event)) throw new TypeError("expected Event");
      const state = eventStates.get(event);
      if (state.dispatching || !event.type) throw new DOMException("event is already being dispatched", "InvalidStateError");
      state.dispatching = true;
      state.target = this;
      state.currentTarget = this;
      state.stopped = false;
      state.immediate = false;
      try {
        const handler = this[`on${event.type}`];
        if (isListener(handler)) callListener(handler, this, event);
        const entries = targetStates.get(this).filter((entry) => entry.type === event.type);
        for (const entry of entries) {
          if (state.immediate) break;
          if (entry.once) this.removeEventListener(entry.type, entry.listener, entry.capture);
          callListener(entry.listener, this, event);
        }
      } finally {
        state.currentTarget = null;
        state.dispatching = false;
      }
      return !state.canceled;
    }
  }

  globalThis.Event = Event;
  globalThis.EventTarget = EventTarget;
  globalThis.__tysel_event = function(type, init) {
    const event = new Event(type, init);
    for (const [key, value] of Object.entries(init || {})) {
      if (!(key in event)) Object.defineProperty(event, key, { value, enumerable: true });
    }
    return event;
  };
})();

// source: web-api/source/url.js
(() => {
  function decodeURIComponentSafe(value) {
    try {
      return decodeURIComponent(String(value).replace(/\+/g, " "));
    } catch {
      return String(value);
    }
  }

  function encodeFormComponent(value) {
    return encodeURIComponent(String(value))
      .replace(/[!'()~]/g, (character) =>
        "%" + character.charCodeAt(0).toString(16).toUpperCase(),
      )
      .replace(/%20/g, "+");
  }

  function splitReference(value) {
    const hashIndex = value.indexOf("#");
    const hash = hashIndex === -1 ? "" : value.slice(hashIndex);
    const withoutHash = hashIndex === -1 ? value : value.slice(0, hashIndex);
    const searchIndex = withoutHash.indexOf("?");
    return {
      pathname: searchIndex === -1 ? withoutHash : withoutHash.slice(0, searchIndex),
      search: searchIndex === -1 ? "" : withoutHash.slice(searchIndex),
      hash,
    };
  }

  function normalizePath(pathname) {
    const absolute = pathname.charAt(0) === "/";
    const trailing = /\/(?:\.{0,2})?$/.test(pathname);
    const segments = [];
    for (const segment of pathname.split("/")) {
      if (!segment || segment === ".") continue;
      if (segment === "..") segments.pop();
      else segments.push(segment);
    }
    let result = (absolute ? "/" : "") + segments.join("/");
    if (absolute && !result) result = "/";
    if (trailing && result !== "/") result += "/";
    return result;
  }

  function parseAbsolute(value) {
    const match = /^([a-zA-Z][a-zA-Z0-9+.-]*:)\/\/([^/?#]*)([^?#]*)(\?[^#]*)?(#.*)?$/.exec(value);
    if (!match) throw new TypeError("Invalid URL");
    const protocol = match[1].toLowerCase();
    const authority = match[2];
    const host = authority.slice(authority.lastIndexOf("@") + 1);
    let hostname = host;
    let port = "";
    if (host.charAt(0) === "[") {
      const bracket = host.indexOf("]");
      if (bracket === -1) throw new TypeError("Invalid URL");
      hostname = host.slice(0, bracket + 1);
      if (host.charAt(bracket + 1) === ":") port = host.slice(bracket + 2);
    } else {
      const colon = host.lastIndexOf(":");
      if (colon !== -1) {
        hostname = host.slice(0, colon);
        port = host.slice(colon + 1);
      }
    }
    if (!hostname) throw new TypeError("Invalid URL");
    const pathname = normalizePath(match[3] || "/");
    const origin = protocol + "//" + authority;
    return {
      protocol,
      origin,
      host,
      hostname,
      port,
      pathname,
      search: match[4] || "",
      hash: match[5] || "",
      href: origin + pathname + (match[4] || "") + (match[5] || ""),
    };
  }

  function resolveUrl(value, base) {
    if (/^[a-zA-Z][a-zA-Z0-9+.-]*:/.test(value)) return parseAbsolute(value);
    if (base == null) throw new TypeError("Invalid URL");
    const parsedBase = parseAbsolute(String(base));
    if (value.slice(0, 2) === "//") return parseAbsolute(parsedBase.protocol + value);

    const reference = splitReference(value);
    let pathname;
    let search = reference.search;
    if (!reference.pathname) {
      pathname = parsedBase.pathname;
      if (!search && value.charAt(0) !== "?") search = parsedBase.search;
    } else if (reference.pathname.charAt(0) === "/") {
      pathname = normalizePath(reference.pathname);
    } else {
      const slash = parsedBase.pathname.lastIndexOf("/");
      pathname = normalizePath(parsedBase.pathname.slice(0, slash + 1) + reference.pathname);
    }
    return parseAbsolute(parsedBase.origin + pathname + search + reference.hash);
  }

  class URLSearchParams {
    constructor(init, update) {
      this._pairs = [];
      this._update = typeof update === "function" ? update : null;
      this._replace(init);
    }
    _replace(init) {
      this._pairs = [];
      if (init == null) return;
      if (typeof init === "string") {
        const text = init.charAt(0) === "?" ? init.slice(1) : init;
        if (!text) return;
        for (const part of text.split("&")) {
          if (!part) continue;
          const eq = part.indexOf("=");
          if (eq === -1) this._pairs.push([decodeURIComponentSafe(part), ""]);
          else {
            this._pairs.push([
              decodeURIComponentSafe(part.slice(0, eq)),
              decodeURIComponentSafe(part.slice(eq + 1)),
            ]);
          }
        }
      } else if (typeof init[Symbol.iterator] === "function") {
        for (const pair of init) {
          if (pair == null || typeof pair[Symbol.iterator] !== "function") {
            throw new TypeError("URLSearchParams sequence entries must be iterable");
          }
          const values = Array.from(pair);
          if (values.length !== 2) {
            throw new TypeError("URLSearchParams sequence entries must contain two items");
          }
          this.append(values[0], values[1]);
        }
      } else {
        for (const key of Object.keys(init)) {
          this._pairs.push([String(key), String(init[key])]);
        }
      }
    }
    _changed() {
      if (this._update) this._update(this.toString());
    }
    get size() {
      return this._pairs.length;
    }
    append(name, value) {
      this._pairs.push([String(name), String(value)]);
      this._changed();
    }
    set(name, value) {
      name = String(name);
      value = String(value);
      const first = this._pairs.findIndex((pair) => pair[0] === name);
      if (first === -1) this._pairs.push([name, value]);
      else {
        this._pairs[first][1] = value;
        this._pairs = this._pairs.filter((pair, index) => pair[0] !== name || index === first);
      }
      this._changed();
    }
    get(name) {
      name = String(name);
      for (const pair of this._pairs) {
        if (pair[0] === name) return pair[1];
      }
      return null;
    }
    getAll(name) {
      name = String(name);
      return this._pairs.filter((pair) => pair[0] === name).map((pair) => pair[1]);
    }
    has(name) {
      name = String(name);
      return this._pairs.some((pair) => pair[0] === name);
    }
    delete(name) {
      name = String(name);
      this._pairs = this._pairs.filter((pair) => pair[0] !== name);
      this._changed();
    }
    sort() {
      this._pairs.sort((left, right) =>
        left[0] < right[0] ? -1 : left[0] > right[0] ? 1 : 0,
      );
      this._changed();
    }
    forEach(callback, thisArg) {
      for (const [name, value] of this._pairs) {
        callback.call(thisArg, value, name, this);
      }
    }
    entries() {
      return this._pairs.map((pair) => pair.slice())[Symbol.iterator]();
    }
    keys() {
      return this._pairs.map((pair) => pair[0])[Symbol.iterator]();
    }
    values() {
      return this._pairs.map((pair) => pair[1])[Symbol.iterator]();
    }
    [Symbol.iterator]() {
      return this.entries();
    }
    toString() {
      return this._pairs
        .map((pair) => encodeFormComponent(pair[0]) + "=" + encodeFormComponent(pair[1]))
        .join("&");
    }
  }

  class URL {
    constructor(url, base) {
      const parsed = resolveUrl(String(url), base);
      this._searchParams = new URLSearchParams(parsed.search, (serialized) => {
        this._search = serialized ? "?" + serialized : "";
        this._commit();
      });
      this._apply(parsed, false);
    }
    _apply(parsed, updateParams = true) {
      this._protocol = parsed.protocol;
      this._host = parsed.host;
      this._hostname = parsed.hostname;
      this._port = parsed.port;
      this._pathname = parsed.pathname;
      this._search = parsed.search;
      this._hash = parsed.hash;
      if (updateParams) this._searchParams._replace(this._search);
      this._commit();
    }
    _commit() {
      this._origin = this._protocol + "//" + this._host;
      this._href = this._origin + this._pathname + this._search + this._hash;
    }
    get href() { return this._href; }
    set href(value) { this._apply(parseAbsolute(String(value))); }
    get protocol() { return this._protocol; }
    set protocol(value) {
      let protocol = String(value);
      if (!protocol.endsWith(":")) protocol += ":";
      if (!/^[a-zA-Z][a-zA-Z0-9+.-]*:$/.test(protocol)) throw new TypeError("Invalid URL protocol");
      this._protocol = protocol.toLowerCase();
      this._commit();
    }
    get origin() { return this._origin; }
    get host() { return this._host; }
    set host(value) {
      const parsed = parseAbsolute(this._protocol + "//" + String(value) + this._pathname);
      this._host = parsed.host;
      this._hostname = parsed.hostname;
      this._port = parsed.port;
      this._commit();
    }
    get hostname() { return this._hostname; }
    set hostname(value) {
      const hostname = String(value);
      const parsed = parseAbsolute(
        this._protocol + "//" + hostname + (this._port ? ":" + this._port : "") + this._pathname,
      );
      this._host = parsed.host;
      this._hostname = parsed.hostname;
      this._commit();
    }
    get port() { return this._port; }
    set port(value) {
      const port = String(value);
      if (port && (!/^\d+$/.test(port) || Number(port) > 65535)) throw new TypeError("Invalid URL port");
      this._port = port;
      this._host = this._hostname + (port ? ":" + port : "");
      this._commit();
    }
    get pathname() { return this._pathname; }
    set pathname(value) {
      let pathname = String(value);
      if (pathname.charAt(0) !== "/") pathname = "/" + pathname;
      this._pathname = normalizePath(pathname);
      this._commit();
    }
    get search() { return this._search; }
    set search(value) {
      const search = String(value);
      this._search = !search ? "" : search.charAt(0) === "?" ? search : "?" + search;
      this._searchParams._replace(this._search);
      this._commit();
    }
    get searchParams() { return this._searchParams; }
    get hash() { return this._hash; }
    set hash(value) {
      const hash = String(value);
      this._hash = !hash ? "" : hash.charAt(0) === "#" ? hash : "#" + hash;
      this._commit();
    }
    toString() {
      return this.href;
    }
    toJSON() {
      return this.href;
    }
  }

  globalThis.URL = URL;
  globalThis.URLSearchParams = URLSearchParams;
})();

// source: web-api/source/http.js
(() => {
  class Headers {
    constructor(init) {
      this._map = {};
      if (!init) return;
      // Arrays have forEach, so the sequence form must be checked first.
      if (Array.isArray(init)) {
        for (const pair of init) this.append(pair[0], pair[1]);
      } else if (typeof init.forEach === "function") {
        init.forEach((value, key) => this.append(key, value));
      } else {
        for (const key of Object.keys(init)) this.append(key, init[key]);
      }
    }
    get(name) {
      const value = this._map[String(name).toLowerCase()];
      return value === undefined ? null : value;
    }
    set(name, value) {
      this._map[String(name).toLowerCase()] = String(value);
    }
    append(name, value) {
      const key = String(name).toLowerCase();
      const prev = this._map[key];
      this._map[key] = prev == null ? String(value) : prev + ", " + String(value);
    }
    has(name) {
      return Object.prototype.hasOwnProperty.call(this._map, String(name).toLowerCase());
    }
    delete(name) {
      delete this._map[String(name).toLowerCase()];
    }
    _names() {
      return Object.keys(this._map).sort();
    }
    forEach(callback, thisArg) {
      for (const key of this._names()) {
        callback.call(thisArg, this._map[key], key, this);
      }
    }
    entries() {
      return this._names().map((key) => [key, this._map[key]])[Symbol.iterator]();
    }
    keys() {
      return this._names()[Symbol.iterator]();
    }
    values() {
      return this._names().map((key) => this._map[key])[Symbol.iterator]();
    }
    [Symbol.iterator]() {
      return this.entries();
    }
  }

  class Request {
    constructor(input, init) {
      init = init || {};
      if (typeof input === "string") {
        this.url = input;
        this.method = String(init.method || "GET").toUpperCase();
        this.headers = new Headers(init.headers);
        this.body = init.body == null ? null : init.body;
        this._stream = init.bodyStream === true;
        this._text = null;
        this.signal = init.signal || null;
      } else {
        if (input.bodyUsed && init.body == null) {
          throw new TypeError("cannot construct from a consumed Request");
        }
        this.url = input.url;
        this.method = String(init.method || input.method || "GET").toUpperCase();
        this.headers = new Headers(init.headers || input.headers);
        this.body = init.body == null ? input.body : init.body;
        this._stream = init.bodyStream === true || (init.body == null && input._stream === true);
        this._text = input._text || null;
        this.signal = init.signal || input.signal || null;
      }
      this._bodyUsed = false;
    }
    get bodyUsed() {
      return this._bodyUsed;
    }
    async text() {
      if (this._bodyUsed) throw new TypeError("body has already been consumed");
      this._bodyUsed = true;
      if (this._text != null) return this._text;
      if (this._stream) {
        const chunks = [];
        for (;;) {
          const chunk = await tysel.readBody();
          if (chunk == null) break;
          chunks.push(chunk);
        }
        this._text = chunks.join("");
        this._stream = false;
        return this._text;
      }
      this._text = this.body == null ? "" : String(this.body);
      return this._text;
    }
    async json() {
      const text = await this.text();
      return text ? JSON.parse(text) : null;
    }
    async arrayBuffer() {
      return new TextEncoder().encode(await this.text()).buffer;
    }
    clone() {
      if (this._stream || this._bodyUsed) {
        throw new TypeError("cannot clone a streaming or consumed request");
      }
      return new Request(this.url, {
        method: this.method,
        headers: this.headers,
        body: this.body,
        signal: this.signal,
      });
    }
  }

  class Response {
    constructor(body, init) {
      init = init || {};
      this.body = body == null ? null : body;
      this.status = init.status || 200;
      this.headers = new Headers(init.headers);
      this._stream = false;
      this._signal = null;
      this._bodyUsed = false;
    }
    get ok() {
      return this.status >= 200 && this.status < 300;
    }
    static json(data, init) {
      init = init || {};
      const headers = new Headers(init.headers);
      if (!headers.get("content-type")) {
        headers.set("content-type", "application/json");
      }
      const body = JSON.stringify(data);
      if (body === undefined) throw new TypeError("data is not JSON serializable");
      return new Response(body, { status: init.status || 200, headers });
    }
    get bodyUsed() {
      return this._bodyUsed;
    }
    async text() {
      if (this._bodyUsed) throw new TypeError("body has already been consumed");
      this._bodyUsed = true;
      if (this._stream) {
        const chunks = [];
        try {
          for (;;) {
            const operation = tysel._httpRead(this._bodyId);
            const chunk = await globalThis.__tysel_awaitOperation(
              operation,
              this._signal,
            );
            if (chunk == null) break;
            chunks.push(chunk);
          }
          this.body = chunks.join("");
          return this.body;
        } finally {
          this._stream = false;
          if (this._abortCleanup) this._abortCleanup();
        }
      }
      return this.body == null ? "" : String(this.body);
    }
    async json() {
      const text = await this.text();
      return text ? JSON.parse(text) : null;
    }
    async arrayBuffer() {
      return new TextEncoder().encode(await this.text()).buffer;
    }
    clone() {
      if (this._stream || this._bodyUsed) {
        throw new TypeError("cannot clone a streaming or consumed response");
      }
      return new Response(this.body, { status: this.status, headers: this.headers });
    }
  }

  globalThis.Headers = Headers;
  globalThis.Request = Request;
  globalThis.Response = Response;
})();

// source: web-api/source/encoding.js
(() => {
  class TextEncoder {
    constructor() {
      this.encoding = "utf-8";
    }
    encode(input) {
      return tysel._utf8Encode(input == null ? "" : String(input));
    }
  }

  class TextDecoder {
    constructor(label, options) {
      const encoding = String(label == null ? "utf-8" : label)
        .trim()
        .toLowerCase()
        .replace(/[_-]/g, "");
      if (encoding !== "utf8") {
        throw new RangeError("TextDecoder only supports utf-8");
      }
      this.encoding = "utf-8";
      this.fatal = Boolean(options && options.fatal);
      this.ignoreBOM = Boolean(options && options.ignoreBOM);
    }
    decode(input) {
      if (input == null) return "";
      let view;
      if (input instanceof ArrayBuffer) view = new Uint8Array(input);
      else if (ArrayBuffer.isView(input)) {
        view = new Uint8Array(input.buffer, input.byteOffset, input.byteLength);
      } else {
        throw new TypeError("expected BufferSource");
      }
      let text = tysel._utf8Decode(view, this.fatal);
      if (this.ignoreBOM && text.charCodeAt(0) === 0xfeff) text = text.slice(1);
      return text;
    }
  }

  globalThis.TextEncoder = TextEncoder;
  globalThis.TextDecoder = TextDecoder;
})();

// source: web-api/source/timers.js
(() => {
  const timers = new Map();
  let nextTimerId = 1;
  let timerGeneration = 0;

  function scheduleTimer(fn, ms, interval, args) {
    if (typeof fn !== "function") {
      throw new TypeError("timer callback must be a function");
    }
    const id = nextTimerId++;
    const delay = Math.max(0, Number(ms) || 0);
    const generation = timerGeneration;
    let cleared = false;
    timers.set(id, () => {
      cleared = true;
    });
    const tick = async () => {
      try {
        await tysel.sleep(delay);
      } catch {
        timers.delete(id);
        return;
      }
      if (cleared || generation !== timerGeneration) {
        timers.delete(id);
        return;
      }
      if (interval) tick();
      else timers.delete(id);
      fn.apply(undefined, args);
    };
    tick();
    return id;
  }

  globalThis.setTimeout = function (fn, ms) {
    return scheduleTimer(fn, ms, false, Array.prototype.slice.call(arguments, 2));
  };
  globalThis.setInterval = function (fn, ms) {
    return scheduleTimer(fn, ms, true, Array.prototype.slice.call(arguments, 2));
  };
  globalThis.clearTimeout = function (id) {
    const clear = timers.get(id);
    if (clear) {
      clear();
      timers.delete(id);
    }
  };
  globalThis.clearInterval = globalThis.clearTimeout;
  globalThis.__tysel_resetTimers = function () {
    timerGeneration++;
    timers.forEach((clear) => clear());
    timers.clear();
  };
})();

// source: web-api/source/abort.js
(() => {
  const signalToken = Object.freeze({});
  const states = new WeakMap();

  function defaultReason() {
    return new DOMException("This operation was aborted", "AbortError");
  }

  class AbortSignal extends EventTarget {
    constructor(token) {
      super();
      if (token !== signalToken) throw new TypeError("Illegal constructor");
      states.set(this, { aborted: false, reason: undefined });
      this.onabort = null;
    }
    static abort(reason) {
      const controller = new AbortController();
      controller.abort(reason);
      return controller.signal;
    }
    static timeout(milliseconds) {
      const delay = Number(milliseconds);
      if (!Number.isFinite(delay) || delay < 0 || delay > 0xffffffff) {
        throw new RangeError("AbortSignal timeout must be an unsigned integer");
      }
      const controller = new AbortController();
      setTimeout(
        () =>
          controller.abort(
            new DOMException("The operation timed out", "TimeoutError"),
          ),
        Math.floor(delay),
      );
      return controller.signal;
    }
    get aborted() {
      return states.get(this).aborted;
    }
    get reason() {
      return states.get(this).reason;
    }
    throwIfAborted() {
      const state = states.get(this);
      if (state.aborted) throw state.reason;
    }
    _abort(reason) {
      const state = states.get(this);
      if (state.aborted) return;
      state.aborted = true;
      state.reason = reason === undefined ? defaultReason() : reason;
      const event = globalThis.__tysel_event("abort");
      this.dispatchEvent(event);
    }
  }

  class AbortController {
    constructor() {
      Object.defineProperty(this, "signal", {
        value: new AbortSignal(signalToken),
        enumerable: true,
      });
    }
    abort(reason) {
      this.signal._abort(reason);
    }
  }

  globalThis.AbortSignal = AbortSignal;
  globalThis.AbortController = AbortController;
})();

// source: web-api/source/crypto.js
(() => {
  class CryptoKey {
    constructor(token, type, extractable, algorithm, usages) {
      if (token !== cryptoKeyToken) throw new TypeError("Illegal constructor");
      Object.defineProperties(this, {
        type: { value: type, enumerable: true },
        extractable: { value: extractable, enumerable: true },
        algorithm: { value: Object.freeze(algorithm), enumerable: true },
        usages: { value: Object.freeze(usages), enumerable: true },
      });
      Object.freeze(this);
    }
  }
  globalThis.CryptoKey = CryptoKey;
  const integerTypedArrays = new Set([
    "[object Int8Array]",
    "[object Uint8Array]",
    "[object Uint8ClampedArray]",
    "[object Int16Array]",
    "[object Uint16Array]",
    "[object Int32Array]",
    "[object Uint32Array]",
    "[object BigInt64Array]",
    "[object BigUint64Array]",
  ]);
  globalThis.crypto = {
    getRandomValues(typedArray) {
      if (!integerTypedArrays.has(Object.prototype.toString.call(typedArray))) {
        throw new DOMException("expected an integer TypedArray", "TypeMismatchError");
      }
      const view = new Uint8Array(
        typedArray.buffer,
        typedArray.byteOffset,
        typedArray.byteLength,
      );
      if (view.byteLength > 65536) {
        throw new DOMException("random value request exceeds 65536 bytes", "QuotaExceededError");
      }
      view.set(tysel._randomBytes(view.byteLength));
      return typedArray;
    },
    subtle: {
      async digest(algorithm, data) {
        const name = normalizeCryptoHash(algorithm);
        return tysel._digest(name, toCryptoBytes(data)).buffer;
      },
      async importKey(format, keyData, algorithm, extractable, keyUsages) {
        if (format !== "raw") throw new DOMException("only raw CryptoKeys are supported", "NotSupportedError");
        const algo = typeof algorithm === "string" ? { name: algorithm } : algorithm || {};
        if (String(algo.name).toUpperCase() !== "HMAC") throw new DOMException("only HMAC keys are supported", "NotSupportedError");
        const hash = normalizeCryptoHash(algo.hash || "SHA-256");
        const usages = Array.from(keyUsages || [], String);
        if (usages.length === 0) {
          throw new DOMException("secret keys require at least one usage", "SyntaxError");
        }
        if (usages.some((usage) => usage !== "sign" && usage !== "verify")) {
          throw new DOMException("HMAC keys only support sign and verify usages", "SyntaxError");
        }
        if (new Set(usages).size !== usages.length) {
          throw new DOMException("HMAC key usages must not contain duplicates", "SyntaxError");
        }
        const bytes = new Uint8Array(toCryptoBytes(keyData));
        const sourceLength = bytes.byteLength * 8;
        if (sourceLength === 0) throw new DOMException("HMAC key data cannot be empty", "DataError");
        let length = sourceLength;
        if (algo.length !== undefined) {
          length = Number(algo.length);
          if (!Number.isInteger(length) || length < 0 || length > 0xffffffff) {
            throw new TypeError("HMAC key length must be an unsigned integer");
          }
          if (length > sourceLength || length <= sourceLength - 8) {
            throw new DOMException("HMAC key length is inconsistent with key data", "DataError");
          }
          if (length % 8 !== 0) {
            bytes[bytes.length - 1] &= (0xff << (8 - (length % 8))) & 0xff;
          }
        }
        // Ask the native implementation to validate the hash before returning a key.
        tysel._digest(hash, new Uint8Array(0));
        const key = new CryptoKey(
          cryptoKeyToken,
          "secret",
          Boolean(extractable),
          { name: "HMAC", hash: Object.freeze({ name: hash }), length },
          usages,
        );
        cryptoKeys.set(key, { hash, bytes });
        return key;
      },
      async sign(algorithm, key, data) {
        const rec = cryptoKeys.get(key);
        if (!rec) throw new TypeError("unknown CryptoKey");
        const name = typeof algorithm === "string" ? algorithm : String(algorithm && algorithm.name || "");
        if (name.toUpperCase() !== "HMAC") throw new DOMException("only HMAC signing is supported", "NotSupportedError");
        if (!key.usages.includes("sign")) throw new DOMException("key does not allow signing", "InvalidAccessError");
        return tysel._hmac(rec.hash, rec.bytes, toCryptoBytes(data)).buffer;
      },
      async verify(algorithm, key, signature, data) {
        const rec = cryptoKeys.get(key);
        if (!rec) throw new TypeError("unknown CryptoKey");
        const name = typeof algorithm === "string" ? algorithm : String(algorithm && algorithm.name || "");
        if (name.toUpperCase() !== "HMAC") throw new DOMException("only HMAC verification is supported", "NotSupportedError");
        if (!key.usages.includes("verify")) throw new DOMException("key does not allow verification", "InvalidAccessError");
        return tysel._hmacVerify(rec.hash, rec.bytes, toCryptoBytes(signature), toCryptoBytes(data));
      },
    },
  };
  const cryptoKeyToken = Object.freeze({});
  const cryptoKeys = new WeakMap();
  function normalizeCryptoHash(algorithm) {
    const raw = typeof algorithm === "string" ? algorithm : String(algorithm && algorithm.name || "");
    const compact = raw.trim().toUpperCase().replace("-", "");
    if (compact === "SHA256") return "SHA-256";
    if (compact === "SHA384") return "SHA-384";
    if (compact === "SHA512") return "SHA-512";
    throw new DOMException(`unsupported digest algorithm ${raw}`, "NotSupportedError");
  }
  function toCryptoBytes(data) {
    if (data instanceof ArrayBuffer) return new Uint8Array(data);
    if (ArrayBuffer.isView(data)) {
      return new Uint8Array(data.buffer, data.byteOffset, data.byteLength);
    }
    throw new TypeError("expected BufferSource");
  }
})();
