// Generated by scripts/build-runtime.mjs. Do not edit.
// source: web-api/source/event.js
(() => {
  const eventStates = new WeakMap();
  const targetStates = new WeakMap();

  function isListener(listener) {
    return typeof listener === "function" ||
      (listener != null && typeof listener.handleEvent === "function");
  }

  function callListener(listener, target, event) {
    try {
      if (typeof listener === "function") listener.call(target, event);
      else listener.handleEvent(event);
    } catch {
      // Listener failures do not propagate through dispatchEvent and cannot
      // terminate native I/O pumps.
    }
  }

  function captureOption(options) {
    return typeof options === "boolean" ? options : Boolean(options && options.capture);
  }

  class Event {
    constructor(type, init) {
      if (arguments.length === 0) throw new TypeError("Event type is required");
      init = init || {};
      eventStates.set(this, {
        target: null,
        currentTarget: null,
        dispatching: false,
        stopped: false,
        immediate: false,
        canceled: false,
      });
      Object.defineProperties(this, {
        type: { value: String(type), enumerable: true },
        bubbles: { value: Boolean(init.bubbles), enumerable: true },
        cancelable: { value: Boolean(init.cancelable), enumerable: true },
        composed: { value: Boolean(init.composed), enumerable: true },
        timeStamp: { value: Date.now(), enumerable: true },
      });
    }
    get target() { return eventStates.get(this).target; }
    get currentTarget() { return eventStates.get(this).currentTarget; }
    get defaultPrevented() { return eventStates.get(this).canceled; }
    stopPropagation() { eventStates.get(this).stopped = true; }
    stopImmediatePropagation() {
      const state = eventStates.get(this);
      state.stopped = true;
      state.immediate = true;
    }
    preventDefault() {
      if (this.cancelable) eventStates.get(this).canceled = true;
    }
  }

  class EventTarget {
    constructor() {
      targetStates.set(this, []);
    }
    addEventListener(type, listener, options) {
      if (!isListener(listener)) return;
      type = String(type);
      const capture = captureOption(options);
      const entries = targetStates.get(this);
      if (entries.some((entry) =>
        entry.type === type && entry.listener === listener && entry.capture === capture
      )) return;
      const entry = {
        type,
        listener,
        capture,
        once: Boolean(options && typeof options === "object" && options.once),
      };
      entries.push(entry);
      const signal = options && typeof options === "object" ? options.signal : null;
      if (signal) {
        if (signal.aborted) this.removeEventListener(type, listener, capture);
        else signal.addEventListener("abort", () => this.removeEventListener(type, listener, capture), { once: true });
      }
    }
    removeEventListener(type, listener, options) {
      const capture = captureOption(options);
      const entries = targetStates.get(this);
      type = String(type);
      targetStates.set(this, entries.filter((entry) =>
        entry.type !== type || entry.listener !== listener || entry.capture !== capture
      ));
    }
    dispatchEvent(event) {
      if (!(event instanceof Event)) throw new TypeError("expected Event");
      const state = eventStates.get(event);
      if (state.dispatching || !event.type) throw new DOMException("event is already being dispatched", "InvalidStateError");
      state.dispatching = true;
      state.target = this;
      state.currentTarget = this;
      state.stopped = false;
      state.immediate = false;
      try {
        const handler = this[`on${event.type}`];
        if (isListener(handler)) callListener(handler, this, event);
        const entries = targetStates.get(this).filter((entry) => entry.type === event.type);
        for (const entry of entries) {
          if (state.immediate) break;
          if (entry.once) this.removeEventListener(entry.type, entry.listener, entry.capture);
          callListener(entry.listener, this, event);
        }
      } finally {
        state.currentTarget = null;
        state.dispatching = false;
      }
      return !state.canceled;
    }
  }

  globalThis.Event = Event;
  globalThis.EventTarget = EventTarget;
  globalThis.__tysel_event = function(type, init) {
    const event = new Event(type, init);
    for (const [key, value] of Object.entries(init || {})) {
      if (!(key in event)) Object.defineProperty(event, key, { value, enumerable: true });
    }
    return event;
  };
})();

// source: web-api/source/url.js
(() => {
  function decodeURIComponentSafe(value) {
    try {
      return decodeURIComponent(String(value).replace(/\+/g, " "));
    } catch {
      return String(value);
    }
  }

  function encodeFormComponent(value) {
    return encodeURIComponent(String(value))
      .replace(/[!'()~]/g, (character) =>
        "%" + character.charCodeAt(0).toString(16).toUpperCase(),
      )
      .replace(/%20/g, "+");
  }

  function splitReference(value) {
    const hashIndex = value.indexOf("#");
    const hash = hashIndex === -1 ? "" : value.slice(hashIndex);
    const withoutHash = hashIndex === -1 ? value : value.slice(0, hashIndex);
    const searchIndex = withoutHash.indexOf("?");
    return {
      pathname: searchIndex === -1 ? withoutHash : withoutHash.slice(0, searchIndex),
      search: searchIndex === -1 ? "" : withoutHash.slice(searchIndex),
      hash,
    };
  }

  function normalizePath(pathname) {
    const absolute = pathname.charAt(0) === "/";
    const trailing = /\/(?:\.{0,2})?$/.test(pathname);
    const segments = [];
    for (const segment of pathname.split("/")) {
      if (!segment || segment === ".") continue;
      if (segment === "..") segments.pop();
      else segments.push(segment);
    }
    let result = (absolute ? "/" : "") + segments.join("/");
    if (absolute && !result) result = "/";
    if (trailing && result !== "/") result += "/";
    return result;
  }

  function parseAbsolute(value) {
    const match = /^([a-zA-Z][a-zA-Z0-9+.-]*:)\/\/([^/?#]*)([^?#]*)(\?[^#]*)?(#.*)?$/.exec(value);
    if (!match) throw new TypeError("Invalid URL");
    const protocol = match[1].toLowerCase();
    const authority = match[2];
    const host = authority.slice(authority.lastIndexOf("@") + 1);
    let hostname = host;
    let port = "";
    if (host.charAt(0) === "[") {
      const bracket = host.indexOf("]");
      if (bracket === -1) throw new TypeError("Invalid URL");
      hostname = host.slice(0, bracket + 1);
      if (host.charAt(bracket + 1) === ":") port = host.slice(bracket + 2);
    } else {
      const colon = host.lastIndexOf(":");
      if (colon !== -1) {
        hostname = host.slice(0, colon);
        port = host.slice(colon + 1);
      }
    }
    if (!hostname) throw new TypeError("Invalid URL");
    const pathname = normalizePath(match[3] || "/");
    const origin = protocol + "//" + authority;
    return {
      protocol,
      origin,
      host,
      hostname,
      port,
      pathname,
      search: match[4] || "",
      hash: match[5] || "",
      href: origin + pathname + (match[4] || "") + (match[5] || ""),
    };
  }

  function resolveUrl(value, base) {
    if (/^[a-zA-Z][a-zA-Z0-9+.-]*:/.test(value)) return parseAbsolute(value);
    if (base == null) throw new TypeError("Invalid URL");
    const parsedBase = parseAbsolute(String(base));
    if (value.slice(0, 2) === "//") return parseAbsolute(parsedBase.protocol + value);

    const reference = splitReference(value);
    let pathname;
    let search = reference.search;
    if (!reference.pathname) {
      pathname = parsedBase.pathname;
      if (!search && value.charAt(0) !== "?") search = parsedBase.search;
    } else if (reference.pathname.charAt(0) === "/") {
      pathname = normalizePath(reference.pathname);
    } else {
      const slash = parsedBase.pathname.lastIndexOf("/");
      pathname = normalizePath(parsedBase.pathname.slice(0, slash + 1) + reference.pathname);
    }
    return parseAbsolute(parsedBase.origin + pathname + search + reference.hash);
  }

  class URLSearchParams {
    constructor(init, update) {
      this._pairs = [];
      this._update = typeof update === "function" ? update : null;
      this._replace(init);
    }
    _replace(init) {
      this._pairs = [];
      if (init == null) return;
      if (typeof init === "string") {
        const text = init.charAt(0) === "?" ? init.slice(1) : init;
        if (!text) return;
        for (const part of text.split("&")) {
          if (!part) continue;
          const eq = part.indexOf("=");
          if (eq === -1) this._pairs.push([decodeURIComponentSafe(part), ""]);
          else {
            this._pairs.push([
              decodeURIComponentSafe(part.slice(0, eq)),
              decodeURIComponentSafe(part.slice(eq + 1)),
            ]);
          }
        }
      } else if (typeof init[Symbol.iterator] === "function") {
        for (const pair of init) {
          if (pair == null || typeof pair[Symbol.iterator] !== "function") {
            throw new TypeError("URLSearchParams sequence entries must be iterable");
          }
          const values = Array.from(pair);
          if (values.length !== 2) {
            throw new TypeError("URLSearchParams sequence entries must contain two items");
          }
          this.append(values[0], values[1]);
        }
      } else {
        for (const key of Object.keys(init)) {
          this._pairs.push([String(key), String(init[key])]);
        }
      }
    }
    _changed() {
      if (this._update) this._update(this.toString());
    }
    get size() {
      return this._pairs.length;
    }
    append(name, value) {
      this._pairs.push([String(name), String(value)]);
      this._changed();
    }
    set(name, value) {
      name = String(name);
      value = String(value);
      const first = this._pairs.findIndex((pair) => pair[0] === name);
      if (first === -1) this._pairs.push([name, value]);
      else {
        this._pairs[first][1] = value;
        this._pairs = this._pairs.filter((pair, index) => pair[0] !== name || index === first);
      }
      this._changed();
    }
    get(name) {
      name = String(name);
      for (const pair of this._pairs) {
        if (pair[0] === name) return pair[1];
      }
      return null;
    }
    getAll(name) {
      name = String(name);
      return this._pairs.filter((pair) => pair[0] === name).map((pair) => pair[1]);
    }
    has(name) {
      name = String(name);
      return this._pairs.some((pair) => pair[0] === name);
    }
    delete(name) {
      name = String(name);
      this._pairs = this._pairs.filter((pair) => pair[0] !== name);
      this._changed();
    }
    sort() {
      this._pairs.sort((left, right) =>
        left[0] < right[0] ? -1 : left[0] > right[0] ? 1 : 0,
      );
      this._changed();
    }
    forEach(callback, thisArg) {
      for (const [name, value] of this._pairs) {
        callback.call(thisArg, value, name, this);
      }
    }
    entries() {
      return this._pairs.map((pair) => pair.slice())[Symbol.iterator]();
    }
    keys() {
      return this._pairs.map((pair) => pair[0])[Symbol.iterator]();
    }
    values() {
      return this._pairs.map((pair) => pair[1])[Symbol.iterator]();
    }
    [Symbol.iterator]() {
      return this.entries();
    }
    toString() {
      return this._pairs
        .map((pair) => encodeFormComponent(pair[0]) + "=" + encodeFormComponent(pair[1]))
        .join("&");
    }
  }

  class URL {
    constructor(url, base) {
      const parsed = resolveUrl(String(url), base);
      this._searchParams = new URLSearchParams(parsed.search, (serialized) => {
        this._search = serialized ? "?" + serialized : "";
        this._commit();
      });
      this._apply(parsed, false);
    }
    _apply(parsed, updateParams = true) {
      this._protocol = parsed.protocol;
      this._host = parsed.host;
      this._hostname = parsed.hostname;
      this._port = parsed.port;
      this._pathname = parsed.pathname;
      this._search = parsed.search;
      this._hash = parsed.hash;
      if (updateParams) this._searchParams._replace(this._search);
      this._commit();
    }
    _commit() {
      this._origin = this._protocol + "//" + this._host;
      this._href = this._origin + this._pathname + this._search + this._hash;
    }
    get href() { return this._href; }
    set href(value) { this._apply(parseAbsolute(String(value))); }
    get protocol() { return this._protocol; }
    set protocol(value) {
      let protocol = String(value);
      if (!protocol.endsWith(":")) protocol += ":";
      if (!/^[a-zA-Z][a-zA-Z0-9+.-]*:$/.test(protocol)) throw new TypeError("Invalid URL protocol");
      this._protocol = protocol.toLowerCase();
      this._commit();
    }
    get origin() { return this._origin; }
    get host() { return this._host; }
    set host(value) {
      const parsed = parseAbsolute(this._protocol + "//" + String(value) + this._pathname);
      this._host = parsed.host;
      this._hostname = parsed.hostname;
      this._port = parsed.port;
      this._commit();
    }
    get hostname() { return this._hostname; }
    set hostname(value) {
      const hostname = String(value);
      const parsed = parseAbsolute(
        this._protocol + "//" + hostname + (this._port ? ":" + this._port : "") + this._pathname,
      );
      this._host = parsed.host;
      this._hostname = parsed.hostname;
      this._commit();
    }
    get port() { return this._port; }
    set port(value) {
      const port = String(value);
      if (port && (!/^\d+$/.test(port) || Number(port) > 65535)) throw new TypeError("Invalid URL port");
      this._port = port;
      this._host = this._hostname + (port ? ":" + port : "");
      this._commit();
    }
    get pathname() { return this._pathname; }
    set pathname(value) {
      let pathname = String(value);
      if (pathname.charAt(0) !== "/") pathname = "/" + pathname;
      this._pathname = normalizePath(pathname);
      this._commit();
    }
    get search() { return this._search; }
    set search(value) {
      const search = String(value);
      this._search = !search ? "" : search.charAt(0) === "?" ? search : "?" + search;
      this._searchParams._replace(this._search);
      this._commit();
    }
    get searchParams() { return this._searchParams; }
    get hash() { return this._hash; }
    set hash(value) {
      const hash = String(value);
      this._hash = !hash ? "" : hash.charAt(0) === "#" ? hash : "#" + hash;
      this._commit();
    }
    toString() {
      return this.href;
    }
    toJSON() {
      return this.href;
    }
  }

  globalThis.URL = URL;
  globalThis.URLSearchParams = URLSearchParams;
})();

// source: web-api/source/utilities.js
(() => {
  globalThis.queueMicrotask = function(callback) {
    if (typeof callback !== "function") throw new TypeError("callback must be a function");
    const generation = globalThis.__tysel_request_generation;
    tysel._queueMicrotask(() => {
      if (generation === globalThis.__tysel_request_generation) callback();
    });
  };
  const alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
  globalThis.btoa = function(input) {
    const text = String(input);
    const output = [];
    for (let i = 0; i < text.length; i += 3) {
      const a = text.charCodeAt(i), b = text.charCodeAt(i + 1), c = text.charCodeAt(i + 2);
      if (a > 255 || b > 255 || c > 255) throw new DOMException("Invalid character", "InvalidCharacterError");
      output.push(alphabet[a >> 2], alphabet[((a & 3) << 4) | ((b || 0) >> 4)],
        i + 1 < text.length ? alphabet[((b & 15) << 2) | ((c || 0) >> 6)] : "=",
        i + 2 < text.length ? alphabet[c & 63] : "=");
    }
    return output.join("");
  };
  globalThis.atob = function(input) {
    let text = String(input).replace(/[\t\n\f\r ]/g, "");
    if (text.length % 4 === 0) text = text.replace(/==?$/, "");
    if (text.length % 4 === 1 || /[^A-Za-z0-9+/]/.test(text)) {
      throw new DOMException("Invalid base64", "InvalidCharacterError");
    }
    let bits = 0, count = 0;
    const output = [];
    for (const char of text) {
      bits = (bits << 6) | alphabet.indexOf(char);
      count += 6;
      if (count >= 8) { count -= 8; output.push(String.fromCharCode((bits >> count) & 255)); }
    }
    return output.join("");
  };
})();

// source: web-api/vendor/web-streams-polyfill/polyfill.js
/*
The MIT License (MIT)

Copyright (c) 2026 Mattias Buelens
Copyright (c) 2016 Diwank Singh Tomer

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/
(() => {
  let constructors;
  let slots = [];
  function load() {
    if (constructors) return;
    // Evaluate against a private global facade: vendor installation must never
    // overwrite an application's replacements or fail on sealed globals.
    constructors = tysel._loadStreams();
    for (const [name, get, set] of slots) {
      const descriptor = Object.getOwnPropertyDescriptor(globalThis, name);
      if (descriptor && descriptor.configurable && descriptor.get === get && descriptor.set === set) {
        Object.defineProperty(globalThis, name, {
          value: constructors[name], writable: true, configurable: true,
        });
      }
    }
    slots = null;
  }
  // Buffered bodies must not trigger loading merely to test instanceof.
  globalThis.__tysel_isReadableStream = value => constructors !== undefined && value instanceof constructors.ReadableStream;
  for (const name of ["ReadableStream","ReadableStreamDefaultController","ReadableByteStreamController","ReadableStreamBYOBRequest","ReadableStreamDefaultReader","ReadableStreamBYOBReader","WritableStream","WritableStreamDefaultController","WritableStreamDefaultWriter","ByteLengthQueuingStrategy","CountQueuingStrategy","TransformStream","TransformStreamDefaultController"]) {
    const get = () => { load(); return constructors[name]; };
    const set = value => {
      load();
      Object.defineProperty(globalThis, name, {value, writable: true, configurable: true});
    };
    slots.push([name, get, set]);
    Object.defineProperty(globalThis, name, {configurable: true, get, set});
  }
})();

// source: web-api/source/http.js
(() => {
  function headerName(name) {
    const key = String(name).toLowerCase();
    if (!/^[!#$%&'*+.^_`|~0-9a-z-]+$/.test(key)) throw new TypeError("invalid header name");
    return key;
  }
  function headerValue(value) {
    const text = String(value).replace(/^[ \t]+|[ \t]+$/g, "");
    if (/[\r\n\0]/.test(text)) throw new TypeError("invalid header value");
    return text;
  }
  function headerIterator(headers, kind) {
    let version = -1, entries, index = 0;
    return {
      [Symbol.iterator]() { return this; },
      next() {
        // Web IDL indexes the current sorted list, including separate cookies.
        // Rebuild only after mutation. Reaching the end does not freeze the list.
        if (version !== headers._version) {
          entries = [];
          for (const key of Object.keys(headers._map).sort()) {
            if (key === "set-cookie") {
              for (const cookie of headers._cookies) entries.push([key, cookie]);
            } else entries.push([key, headers._map[key]]);
          }
          version = headers._version;
        }
        if (index >= entries.length) return {value: undefined, done: true};
        const pair = entries[index++];
        return {value: kind === "keys" ? pair[0] : kind === "values" ? pair[1] : pair, done: false};
      },
    };
  }

  class Headers {
    constructor(init) {
      this._map = Object.create(null);
      this._cookies = [];
      this._version = 0;
      if (init == null) return;
      if (typeof init[Symbol.iterator] === "function") {
        for (const item of init) {
          const pair = Array.from(item);
          if (pair.length !== 2) throw new TypeError("header pair must have two items");
          this.append(pair[0], pair[1]);
        }
      } else {
        for (const key of Object.keys(init)) this.append(key, init[key]);
      }
    }
    get(name) { return this._map[headerName(name)] ?? null; }
    getSetCookie() { return this._cookies.slice(); }
    set(name, value) {
      const key = headerName(name), text = headerValue(value);
      this._map[key] = text;
      this._version++;
      if (key === "set-cookie") this._cookies = [text];
    }
    append(name, value) {
      const key = headerName(name), text = headerValue(value);
      const prev = this._map[key];
      this._map[key] = prev == null ? text : prev + ", " + text;
      this._version++;
      if (key === "set-cookie") this._cookies.push(text);
    }
    has(name) { return Object.hasOwn(this._map, headerName(name)); }
    delete(name) {
      const key = headerName(name);
      delete this._map[key];
      this._version++;
      if (key === "set-cookie") this._cookies = [];
    }
    entries() { return headerIterator(this, "entries"); }
    keys() { return headerIterator(this, "keys"); }
    values() { return headerIterator(this, "values"); }
    forEach(callback, thisArg) { for (const [key, value] of this) callback.call(thisArg, value, key, this); }
    [Symbol.iterator]() { return this.entries(); }
  }

  function bodyBytes(body) {
    if (globalThis.__tysel_isReadableStream(body)) throw new TypeError("streaming uploads are not supported");
    if (body == null) return new Uint8Array(0);
    if (Array.isArray(body)) {
      const chunks = body.map(bodyBytes);
      return joinBytes(chunks, chunks.reduce((size, chunk) => size + chunk.byteLength, 0));
    }
    if (body instanceof ArrayBuffer) return new Uint8Array(body);
    if (ArrayBuffer.isView(body)) {
      return new Uint8Array(body.buffer, body.byteOffset, body.byteLength);
    }
    return new TextEncoder().encode(String(body));
  }

  function copyBody(body) {
    return body instanceof ArrayBuffer || ArrayBuffer.isView(body)
      ? bodyBytes(body).slice()
      : body;
  }

  function copyResponseBody(body) {
    if (!Array.isArray(body)) return copyBody(body);
    // Snapshot both the chunk list and each view's selected bytes. Native
    // emission can then handle every public ArrayBufferView as Uint8Array.
    return Array.from(body, (chunk) => {
      if (typeof chunk !== "string" && !(chunk instanceof ArrayBuffer) && !ArrayBuffer.isView(chunk)) {
        throw new TypeError("response chunk must be a string or BufferSource");
      }
      return copyBody(chunk);
    });
  }

  function joinBytes(chunks, length) {
    if (chunks.length === 1) return chunks[0];
    const bytes = new Uint8Array(length);
    let offset = 0;
    for (const chunk of chunks) {
      bytes.set(chunk, offset);
      offset += chunk.byteLength;
    }
    return bytes;
  }

  function used(owner) {
    // Adapter to the pinned web-streams-polyfill's disturbed flag. Covered by
    // reader/pipe/async-iteration lifecycle tests when updating the vendor.
    return owner._bodyUsed || Boolean(owner._bodyStream && owner._bodyStream._disturbed);
  }
  function getBody(owner) {
    if (owner._bodyStream) return owner._bodyStream;
    if (!owner._stream && owner._body == null) return null;
    if (owner._bodyUsed) {
      // The buffered fast path consumed the body without initializing Streams.
      // Materialize the same closed, disturbed, unlocked state as consumeBytes.
      // A public read marks disturbance synchronously without vendor field writes.
      const stream = new ReadableStream({ start(controller) { controller.close(); } });
      const reader = stream.getReader();
      reader.read();
      reader.releaseLock();
      owner._bodyStream = stream;
      return stream;
    }
    const host = owner._stream;
    const generation = owner._generation;
    let operation = null;
    let index = 0;
    const chunks = Array.isArray(owner._body) ? owner._body : [owner._body];
    owner._bodyStream = new ReadableStream({
      async pull(controller) {
        if (used(owner) && owner._bodyUsed) throw new TypeError("body has already been consumed");
        if (host) {
          if (generation !== globalThis.__tysel_request_generation) throw new TypeError("body belongs to a completed request");
          operation = owner instanceof Request ? tysel._readBodyOp() : tysel._httpRead(owner._bodyId);
          try {
            const chunk = await globalThis.__tysel_awaitOperation(operation, owner._signal || owner.signal);
            if (chunk == null) {
              controller.close();
              if (owner._abortCleanup) owner._abortCleanup();
            } else controller.enqueue(chunk);
          } finally { operation = null; }
        } else {
          if (index < chunks.length) controller.enqueue(bodyBytes(chunks[index++]));
          if (index === chunks.length) controller.close();
        }
      },
      cancel() {
        if (host && generation === globalThis.__tysel_request_generation) {
          if (operation) tysel._cancelOp(operation.id);
          if (owner instanceof Request) tysel._cancelRequestBody();
          else tysel._httpCancelBody(owner._bodyId);
        }
        if (owner._abortCleanup) owner._abortCleanup();
      },
    }, { highWaterMark: 0 });
    return owner._bodyStream;
  }
  async function consumeBytes(owner) {
    if (used(owner)) throw new TypeError("body has already been consumed");
    if (!owner._stream && !owner._bodyStream) {
      owner._bodyUsed = true;
      return bodyBytes(owner._body);
    }
    const reader = getBody(owner).getReader();
    const chunks = [];
    let length = 0;
    try {
      for (;;) {
        const {value: chunk, done} = await reader.read();
        if (done) break;
        if (!(chunk instanceof Uint8Array)) throw new TypeError("HTTP stream chunks must be Uint8Array");
        if (chunk.byteLength) { chunks.push(chunk); length += chunk.byteLength; }
      }
      return joinBytes(chunks, length);
    } catch (error) {
      // Cleanup must not delay the original failure if user cancellation hangs.
      try { reader.cancel(error).catch(() => {}); } catch (_) {}
      throw error;
    } finally { owner._bodyUsed = true; reader.releaseLock(); }
  }
  async function consumeText(owner) {
    if (!owner._stream && !owner._bodyStream && typeof owner._body === "string") {
      if (used(owner)) throw new TypeError("body has already been consumed");
      owner._bodyUsed = true;
      return owner._body.charCodeAt(0) === 0xfeff ? owner._body.slice(1) : owner._body;
    }
    return new TextDecoder().decode(await consumeBytes(owner));
  }
  async function consumeArrayBuffer(owner) {
    const ownsBytes = owner._stream || owner._bodyStream || (Array.isArray(owner._body) && owner._body.length !== 1);
    const bytes = await consumeBytes(owner);
    // A user-supplied stream can retain its chunks: return independent bytes.
    return ownsBytes && !owner._customStream && bytes.byteOffset === 0 && bytes.byteLength === bytes.buffer.byteLength
      ? bytes.buffer : bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength);
  }

  globalThis.__tysel_bodyBytes = bodyBytes;
  globalThis.__tysel_consumeBytes = consumeBytes;

  class Request {
    constructor(input, init) {
      init = init || {};
      if (globalThis.__tysel_isReadableStream(init.body)) throw new TypeError("streaming uploads are not supported");
      if (typeof input === "string") {
        this.url = input;
        this.method = String(init.method || "GET").toUpperCase();
        this.headers = new Headers(init.headers);
        this._body = init.body == null ? null : copyBody(init.body);
        this._stream = init.bodyStream === true;
        this.signal = init.signal || null;
      } else {
        if ((input.bodyUsed || (input._bodyStream && input._bodyStream.locked)) && init.body == null) {
          throw new TypeError("cannot construct from a consumed Request");
        }
        this.url = input.url;
        this.method = String(init.method || input.method || "GET").toUpperCase();
        this.headers = new Headers(init.headers || input.headers);
        this._body = copyBody(init.body == null ? input._body : init.body);
        this._stream = init.bodyStream === true || (init.body == null && input._stream === true);
        this.signal = init.signal || input.signal || null;
      }
      this._generation = typeof input !== "string" && init.body == null && input._stream
        ? input._generation : globalThis.__tysel_request_generation;
      this._bodyUsed = false;
      this._bodyStream = null;
      this._customStream = false;
    }
    get bodyUsed() {
      return used(this);
    }
    get body() { return getBody(this); }
    async text() { return consumeText(this); }
    async json() { return JSON.parse(await this.text()); }
    async arrayBuffer() { return consumeArrayBuffer(this); }
    clone() {
      if (this._stream || this._customStream || used(this) || (this._bodyStream && this._bodyStream.locked)) {
        throw new TypeError("cannot clone a streaming or consumed request");
      }
      return new Request(this.url, {
        method: this.method,
        headers: this.headers,
        body: this._body,
        signal: this.signal,
      });
    }
  }

  class Response {
    constructor(body, init) {
      init = init || {};
      const stream = globalThis.__tysel_isReadableStream(body);
      if (stream && (body.locked || body._disturbed)) throw new TypeError("body stream is locked or consumed");
      this._body = stream ? null : body == null ? null : copyResponseBody(body);
      this.status = init.status || 200;
      this.headers = new Headers(init.headers);
      this._stream = false;
      this._signal = null;
      this._generation = globalThis.__tysel_request_generation;
      this._bodyUsed = false;
      this._bodyStream = null;
      this._customStream = stream;
      if (this._customStream) this._bodyStream = body;
    }
    get ok() {
      return this.status >= 200 && this.status < 300;
    }
    static json(data, init) {
      init = init || {};
      const body = JSON.stringify(data);
      if (body === undefined) throw new TypeError("data is not JSON serializable");
      // The constructor snapshots headers once. Building another Headers here
      // would iterate, sort and revalidate the same list a second time.
      const response = new Response(body, init);
      if (!response.headers.get("content-type")) {
        response.headers.set("content-type", "application/json");
      }
      return response;
    }
    get bodyUsed() {
      return used(this);
    }
    get body() { return getBody(this); }
    async text() { return consumeText(this); }
    async json() { return JSON.parse(await this.text()); }
    async arrayBuffer() { return consumeArrayBuffer(this); }
    clone() {
      if (this._stream || this._customStream || used(this) || (this._bodyStream && this._bodyStream.locked)) {
        throw new TypeError("cannot clone a streaming or consumed response");
      }
      return new Response(this._body, { status: this.status, headers: this.headers });
    }
  }

  globalThis.__tysel_responseBody = response => {
    if (used(response)) throw new TypeError("response body has already been consumed");
    if (response._bodyStream && response._bodyStream.locked) throw new TypeError("response body is locked");
    return response._stream || response._bodyStream ? response.body : response._body;
  };
  globalThis.__tysel_headerPairs = headers => Array.from(headers);
  globalThis.__tysel_pumpResponse = async function(body, write, closed) {
    const reader = body.getReader();
    let stopped = false;
    const pump = async () => {
      for (;;) {
        const {value, done} = await reader.read();
        if (done || stopped) break;
        if (!(value instanceof Uint8Array)) throw new TypeError("HTTP stream chunks must be Uint8Array");
        await write(value);
      }
    };
    try {
      // One race per response, not per chunk: pending reactions stay bounded.
      await Promise.race([pump(), closed.promise.then(() => {
        throw new TypeError("response consumer closed");
      })]);
    } catch (error) {
      stopped = true;
      // Invoke cleanup, but an application's pending cancel promise must not
      // keep the worker assigned after the consumer has disconnected.
      try { reader.cancel(error).catch(() => {}); } catch (_) {}
      throw error;
    } finally {
      stopped = true;
      tysel._cancelOp(closed.id);
      reader.releaseLock();
    }
  };
  globalThis.Headers = Headers;
  globalThis.Request = Request;
  globalThis.Response = Response;
})();

// source: web-api/source/encoding.js
(() => {
  class TextEncoder {
    constructor() {
      this.encoding = "utf-8";
    }
    encode(input) {
      return tysel._utf8Encode(input == null ? "" : String(input));
    }
  }

  class TextDecoder {
    constructor(label, options) {
      const encoding = String(label == null ? "utf-8" : label)
        .trim()
        .toLowerCase()
        .replace(/[_-]/g, "");
      if (encoding !== "utf8") {
        throw new RangeError("TextDecoder only supports utf-8");
      }
      this.encoding = "utf-8";
      this.fatal = Boolean(options && options.fatal);
      this.ignoreBOM = Boolean(options && options.ignoreBOM);
      this._pending = new Uint8Array(0);
      this._bomSeen = false;
    }
    decode(input, options) {
      let view;
      if (input == null) view = new Uint8Array(0);
      else if (input instanceof ArrayBuffer) view = new Uint8Array(input);
      else if (ArrayBuffer.isView(input)) view = new Uint8Array(input.buffer, input.byteOffset, input.byteLength);
      else throw new TypeError("expected BufferSource");
      const stream = Boolean(options && options.stream);
      if (this._pending.length) {
        const joined = new Uint8Array(this._pending.length + view.byteLength);
        joined.set(this._pending); joined.set(view, this._pending.length); view = joined;
      }
      this._pending = new Uint8Array(0);
      if (stream && view.length) {
        let start = view.length - 1;
        while (start > 0 && view[start] >= 128 && view[start] <= 191 && view.length - start < 4) start--;
        const lead = view[start];
        const required = lead >= 194 && lead <= 223 ? 2 : lead >= 224 && lead <= 239 ? 3 : lead >= 240 && lead <= 244 ? 4 : 0;
        const available = view.length - start;
        const second = view[start + 1];
        const validSecond = available < 2 || (second >= 128 && second <= 191
          && !(lead === 224 && second < 160) && !(lead === 237 && second > 159)
          && !(lead === 240 && second < 144) && !(lead === 244 && second > 143));
        if (required > available && validSecond) {
          this._pending = view.slice(start);
          view = view.subarray(0, start);
        }
      }
      try {
        let text = tysel._utf8Decode(view, this.fatal);
        if (text.length && !this._bomSeen) {
          this._bomSeen = true;
          if (!this.ignoreBOM && text.charCodeAt(0) === 0xfeff) text = text.slice(1);
        }
        if (!stream) { this._pending = new Uint8Array(0); this._bomSeen = false; }
        return text;
      } catch (error) {
        this._pending = new Uint8Array(0); this._bomSeen = false;
        throw error;
      }
    }
  }

  class TextDecoderStream {
    constructor(label, options) {
      const decoder = new TextDecoder(label, options);
      const transform = new TransformStream({
        transform(chunk, controller) {
          const text = decoder.decode(chunk, {stream: true});
          if (text) controller.enqueue(text);
        },
        flush(controller) { const text = decoder.decode(); if (text) controller.enqueue(text); },
      });
      for (const key of ["encoding", "fatal", "ignoreBOM"]) Object.defineProperty(this, key, {value: decoder[key], enumerable: true});
      Object.defineProperties(this, {readable: {value: transform.readable}, writable: {value: transform.writable}});
    }
  }
  globalThis.TextDecoderStream = TextDecoderStream;

  globalThis.TextEncoder = TextEncoder;
  globalThis.TextDecoder = TextDecoder;
})();

// source: web-api/source/timers.js
(() => {
  const timers = new Map();
  let nextTimerId = 1;
  let timerGeneration = 0;

  function scheduleTimer(fn, ms, interval, args) {
    if (typeof fn !== "function") {
      throw new TypeError("timer callback must be a function");
    }
    const id = nextTimerId++;
    const delay = Math.max(0, Number(ms) || 0);
    const generation = timerGeneration;
    let cleared = false;
    timers.set(id, () => {
      cleared = true;
    });
    const tick = async () => {
      try {
        await tysel.sleep(delay);
      } catch {
        timers.delete(id);
        return;
      }
      if (cleared || generation !== timerGeneration) {
        timers.delete(id);
        return;
      }
      if (interval) tick();
      else timers.delete(id);
      fn.apply(undefined, args);
    };
    tick();
    return id;
  }

  globalThis.setTimeout = function (fn, ms) {
    return scheduleTimer(fn, ms, false, Array.prototype.slice.call(arguments, 2));
  };
  globalThis.setInterval = function (fn, ms) {
    return scheduleTimer(fn, ms, true, Array.prototype.slice.call(arguments, 2));
  };
  globalThis.clearTimeout = function (id) {
    const clear = timers.get(id);
    if (clear) {
      clear();
      timers.delete(id);
    }
  };
  globalThis.clearInterval = globalThis.clearTimeout;
  globalThis.__tysel_resetTimers = function () {
    timerGeneration++;
    timers.forEach((clear) => clear());
    timers.clear();
  };
})();

// source: web-api/source/abort.js
(() => {
  const signalToken = Object.freeze({});
  const states = new WeakMap();

  // Held values contain only weak source references, never the dependent.
  const collected = new FinalizationRegistry(links => {
    for (const [source, dependent] of links) {
      const signal = source.deref();
      if (signal) states.get(signal).followers.delete(dependent);
    }
  });

  function defaultReason() {
    return new DOMException("This operation was aborted", "AbortError");
  }

  class AbortSignal extends EventTarget {
    constructor(token) {
      super();
      if (token !== signalToken) throw new TypeError("Illegal constructor");
      states.set(this, { aborted: false, reason: undefined, followers: new Set() });
      this.onabort = null;
    }
    static abort(reason) {
      const controller = new AbortController();
      controller.abort(reason);
      return controller.signal;
    }
    static any(signals) {
      if (signals == null || typeof signals[Symbol.iterator] !== "function") {
        throw new TypeError("expected an iterable of AbortSignal");
      }
      const list = Array.from(signals);
      for (const signal of list) if (!states.has(signal)) throw new TypeError("expected AbortSignal");
      const controller = new AbortController();
      const aborted = list.find(signal => signal.aborted);
      if (aborted) { controller.abort(aborted.reason); return controller.signal; }
      const dependent = new WeakRef(controller.signal);
      const links = [];
      for (const signal of new Set(list)) {
        states.get(signal).followers.add(dependent);
        links.push([new WeakRef(signal), dependent]);
      }
      const state = states.get(controller.signal);
      state.links = links;
      // A live dependent keeps its propagation path alive, including temporary
      // intermediate composites. The reverse edges remain weak.
      state.sources = list;
      // This QuickJS version retains unregister tokens: never use the target.
      if (links.length) collected.register(controller.signal, links, links);
      return controller.signal;
    }
    static timeout(milliseconds) {
      const delay = Number(milliseconds);
      if (!Number.isFinite(delay) || delay < 0 || delay > 0xffffffff) {
        throw new RangeError("AbortSignal timeout must be an unsigned integer");
      }
      const controller = new AbortController();
      setTimeout(
        () =>
          controller.abort(
            new DOMException("The operation timed out", "TimeoutError"),
          ),
        Math.floor(delay),
      );
      return controller.signal;
    }
    get aborted() {
      return states.get(this).aborted;
    }
    get reason() {
      return states.get(this).reason;
    }
    throwIfAborted() {
      const state = states.get(this);
      if (state.aborted) throw state.reason;
    }
    _abort(reason) {
      const state = states.get(this);
      if (state.aborted) return;
      const pending = [this];
      const value = reason === undefined ? defaultReason() : reason;
      // Mark the complete dependency graph before running any user callback.
      state.aborted = true;
      state.reason = value;
      for (let i = 0; i < pending.length; i++) {
        const current = states.get(pending[i]);
        for (const reference of current.followers) {
          const signal = reference.deref();
          if (!signal) continue;
          const next = states.get(signal);
          if (next.aborted) continue;
          next.aborted = true;
          next.reason = value;
          pending.push(signal);
        }
        current.followers.clear();
      }
      for (const signal of pending) {
        const current = states.get(signal);
        for (const [source, dependent] of current.links || []) {
          const parent = source.deref();
          if (parent) states.get(parent).followers.delete(dependent);
        }
        if (current.links) collected.unregister(current.links);
        current.links = undefined;
        current.sources = undefined;
      }
      for (const signal of pending) signal.dispatchEvent(globalThis.__tysel_event("abort"));
    }
  }

  class AbortController {
    constructor() {
      Object.defineProperty(this, "signal", {
        value: new AbortSignal(signalToken),
        enumerable: true,
      });
    }
    abort(reason) {
      this.signal._abort(reason);
    }
  }

  globalThis.AbortSignal = AbortSignal;
  globalThis.AbortController = AbortController;
})();

// source: web-api/source/crypto.js
(() => {
  class CryptoKey {
    constructor(token, type, extractable, algorithm, usages) {
      if (token !== cryptoKeyToken) throw new TypeError("Illegal constructor");
      Object.defineProperties(this, {
        type: { value: type, enumerable: true },
        extractable: { value: extractable, enumerable: true },
        algorithm: { value: Object.freeze(algorithm), enumerable: true },
        usages: { value: Object.freeze(usages), enumerable: true },
      });
      Object.freeze(this);
    }
  }
  globalThis.CryptoKey = CryptoKey;
  const integerTypedArrays = new Set([
    "[object Int8Array]",
    "[object Uint8Array]",
    "[object Uint8ClampedArray]",
    "[object Int16Array]",
    "[object Uint16Array]",
    "[object Int32Array]",
    "[object Uint32Array]",
    "[object BigInt64Array]",
    "[object BigUint64Array]",
  ]);
  globalThis.crypto = {
    randomUUID() {
      const bytes = tysel._randomBytes(16);
      bytes[6] = (bytes[6] & 15) | 64;
      bytes[8] = (bytes[8] & 63) | 128;
      const hex = Array.from(bytes, b => b.toString(16).padStart(2, "0")).join("");
      return `${hex.slice(0,8)}-${hex.slice(8,12)}-${hex.slice(12,16)}-${hex.slice(16,20)}-${hex.slice(20)}`;
    },
    getRandomValues(typedArray) {
      if (!integerTypedArrays.has(Object.prototype.toString.call(typedArray))) {
        throw new DOMException("expected an integer TypedArray", "TypeMismatchError");
      }
      const view = new Uint8Array(
        typedArray.buffer,
        typedArray.byteOffset,
        typedArray.byteLength,
      );
      if (view.byteLength > 65536) {
        throw new DOMException("random value request exceeds 65536 bytes", "QuotaExceededError");
      }
      view.set(tysel._randomBytes(view.byteLength));
      return typedArray;
    },
    subtle: {
      async digest(algorithm, data) {
        const name = normalizeCryptoHash(algorithm);
        return tysel._digest(name, toCryptoBytes(data)).buffer;
      },
      async importKey(format, keyData, algorithm, extractable, keyUsages) {
        if (format !== "raw") throw new DOMException("only raw CryptoKeys are supported", "NotSupportedError");
        const algo = typeof algorithm === "string" ? { name: algorithm } : algorithm || {};
        if (String(algo.name).toUpperCase() !== "HMAC") throw new DOMException("only HMAC keys are supported", "NotSupportedError");
        const hash = normalizeCryptoHash(algo.hash || "SHA-256");
        const usages = Array.from(keyUsages || [], String);
        if (usages.length === 0) {
          throw new DOMException("secret keys require at least one usage", "SyntaxError");
        }
        if (usages.some((usage) => usage !== "sign" && usage !== "verify")) {
          throw new DOMException("HMAC keys only support sign and verify usages", "SyntaxError");
        }
        if (new Set(usages).size !== usages.length) {
          throw new DOMException("HMAC key usages must not contain duplicates", "SyntaxError");
        }
        const bytes = new Uint8Array(toCryptoBytes(keyData));
        const sourceLength = bytes.byteLength * 8;
        if (sourceLength === 0) throw new DOMException("HMAC key data cannot be empty", "DataError");
        let length = sourceLength;
        if (algo.length !== undefined) {
          length = Number(algo.length);
          if (!Number.isInteger(length) || length < 0 || length > 0xffffffff) {
            throw new TypeError("HMAC key length must be an unsigned integer");
          }
          if (length > sourceLength || length <= sourceLength - 8) {
            throw new DOMException("HMAC key length is inconsistent with key data", "DataError");
          }
          if (length % 8 !== 0) {
            bytes[bytes.length - 1] &= (0xff << (8 - (length % 8))) & 0xff;
          }
        }
        // Ask the native implementation to validate the hash before returning a key.
        tysel._digest(hash, new Uint8Array(0));
        const key = new CryptoKey(
          cryptoKeyToken,
          "secret",
          Boolean(extractable),
          { name: "HMAC", hash: Object.freeze({ name: hash }), length },
          usages,
        );
        cryptoKeys.set(key, { hash, bytes });
        return key;
      },
      async sign(algorithm, key, data) {
        const rec = cryptoKeys.get(key);
        if (!rec) throw new TypeError("unknown CryptoKey");
        const name = typeof algorithm === "string" ? algorithm : String(algorithm && algorithm.name || "");
        if (name.toUpperCase() !== "HMAC") throw new DOMException("only HMAC signing is supported", "NotSupportedError");
        if (!key.usages.includes("sign")) throw new DOMException("key does not allow signing", "InvalidAccessError");
        return tysel._hmac(rec.hash, rec.bytes, toCryptoBytes(data)).buffer;
      },
      async verify(algorithm, key, signature, data) {
        const rec = cryptoKeys.get(key);
        if (!rec) throw new TypeError("unknown CryptoKey");
        const name = typeof algorithm === "string" ? algorithm : String(algorithm && algorithm.name || "");
        if (name.toUpperCase() !== "HMAC") throw new DOMException("only HMAC verification is supported", "NotSupportedError");
        if (!key.usages.includes("verify")) throw new DOMException("key does not allow verification", "InvalidAccessError");
        return tysel._hmacVerify(rec.hash, rec.bytes, toCryptoBytes(signature), toCryptoBytes(data));
      },
    },
  };
  const cryptoKeyToken = Object.freeze({});
  const cryptoKeys = new WeakMap();
  function normalizeCryptoHash(algorithm) {
    const raw = typeof algorithm === "string" ? algorithm : String(algorithm && algorithm.name || "");
    const compact = raw.trim().toUpperCase().replace("-", "");
    if (compact === "SHA256") return "SHA-256";
    if (compact === "SHA384") return "SHA-384";
    if (compact === "SHA512") return "SHA-512";
    throw new DOMException(`unsupported digest algorithm ${raw}`, "NotSupportedError");
  }
  function toCryptoBytes(data) {
    if (data instanceof ArrayBuffer) return new Uint8Array(data);
    if (ArrayBuffer.isView(data)) {
      return new Uint8Array(data.buffer, data.byteOffset, data.byteLength);
    }
    throw new TypeError("expected BufferSource");
  }
})();
