use std::path::PathBuf;

use tysel_engine_wasm::{CompiledComponent, ComponentEngineConfig, WasmComponentEngine};

fn compile_fixture(variable: &str) -> (WasmComponentEngine, CompiledComponent) {
    let mut path = std::env::var_os(variable)
        .map(PathBuf::from)
        .unwrap_or_else(|| panic!("{variable} must point to a generated component fixture"));
    if path.is_relative() {
        path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..").join(path);
    }
    let source = std::fs::read(&path)
        .unwrap_or_else(|error| panic!("failed to read {}: {error}", path.display()));
    let engine = WasmComponentEngine::new(ComponentEngineConfig::default()).unwrap();
    let component = engine.compile(&source).unwrap();
    (engine, component)
}

#[test]
#[ignore = "requires a Rust SDK component generated by CI"]
fn rust_sdk_fixture_matches_the_host_contract() {
    let (engine, component) = compile_fixture("TYSEL_RUST_COMPONENT_FIXTURE");
    assert!(component.required_imports().is_empty());
    assert!(component.wasi_runtime_imports().is_empty());
    assert_eq!(
        engine.invoke_json(&component, r#"{"value":{"language":"rust"}}"#).unwrap(),
        r#"{"value":{"language":"rust"}}"#
    );
}

#[test]
#[ignore = "requires a Go SDK component generated by CI"]
fn go_sdk_fixture_matches_the_host_contract_with_restricted_wasi() {
    let (engine, component) = compile_fixture("TYSEL_GO_COMPONENT_FIXTURE");
    assert!(component.required_imports().is_empty());
    assert!(!component.wasi_runtime_imports().is_empty());
    assert_eq!(
        engine.invoke_json(&component, r#"{"value":{"language":"go"}}"#).unwrap(),
        r#"{"value":{"language":"go"}}"#
    );
}
