import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

import {
  bootstrap,
  runtimeJsVersion,
  runtimeLayers,
} from "../bootstrap/index.ts";
import { webApiVersion } from "../web-api/index.ts";

test("bootstrap completes without replacing host globals", () => {
  const originalFetch = globalThis.fetch;

  assert.equal(bootstrap(), undefined);
  assert.equal(globalThis.fetch, originalFetch);
});

test("web API version is a stable semantic version", () => {
  assert.match(webApiVersion, /^\d+\.\d+\.\d+$/);
  assert.equal(webApiVersion, "0.1.0");
  assert.equal(runtimeJsVersion, webApiVersion);
  assert.deepEqual(runtimeLayers, ["web-api", "capability-client", "durable"]);
});

test("QuickJS embeds runtime-js as its single JavaScript source", () => {
  const webApi = readFileSync(new URL("../web-api/runtime.js", import.meta.url), "utf8");
  const capabilities = readFileSync(
    new URL("../capability-client/runtime.js", import.meta.url),
    "utf8",
  );
  const durable = readFileSync(new URL("../durable/runtime.js", import.meta.url), "utf8");
  const fetchRust = readFileSync(
    new URL("../../crates/tysel-engine-qjs/src/fetch.rs", import.meta.url),
    "utf8",
  );
  const hostRust = readFileSync(
    new URL("../../crates/tysel-engine-qjs/src/host.rs", import.meta.url),
    "utf8",
  );
  const isolateRust = readFileSync(
    new URL("../../crates/tysel-engine-qjs/src/isolate.rs", import.meta.url),
    "utf8",
  );
  const taskRust = readFileSync(
    new URL("../../crates/tysel-engine-qjs/src/task_module.rs", import.meta.url),
    "utf8",
  );

  assert.match(webApi, /globalThis\.Response = Response/);
  assert.match(capabilities, /globalThis\.tysel\.sqlite/);
  assert.match(durable, /globalThis\.tysel\.durable = durable/);
  assert.match(fetchRust, /include_str!\("\.\.\/\.\.\/\.\.\/runtime-js\/web-api\/runtime\.js"\)/);
  assert.match(hostRust, /runtime-js\/capability-client\/runtime\.js/);
  assert.match(hostRust, /runtime-js\/durable\/runtime\.js/);
  assert.match(fetchRust, /runtime-js\/bootstrap\/fetch\.js/);
  assert.match(isolateRust, /runtime-js\/bootstrap\/durable-input\.js/);
  assert.match(isolateRust, /runtime-js\/bootstrap\/durable-task\.js/);
  assert.match(taskRust, /runtime-js\/bootstrap\/task-inspect\.js/);
  assert.match(taskRust, /runtime-js\/bootstrap\/durable-inspect\.js/);
  assert.match(taskRust, /runtime-js\/bootstrap\/task-invoke\.js/);
  assert.match(webApi, /^\/\/ Generated by scripts\/build-runtime\.mjs/);
  assert.match(webApi, /source: web-api\/source\/http\.js/);
  assert.match(capabilities, /source: capability-client\/source\/websocket\.js/);
  assert.match(durable, /source: durable\/source\/helpers\.part\.js/);
});

test("compatibility manifest identifies the embedded runtime boundary", () => {
  const manifest = JSON.parse(
    readFileSync(new URL("../compatibility.json", import.meta.url), "utf8"),
  );
  const packageJson = JSON.parse(
    readFileSync(new URL("../package.json", import.meta.url), "utf8"),
  );
  const engineRust = readFileSync(
    new URL("../../crates/tysel-engine-qjs/src/lib.rs", import.meta.url),
    "utf8",
  );

  assert.equal(manifest.schemaVersion, 2);
  assert.equal(manifest.runtimeJsVersion, runtimeJsVersion);
  assert.equal(manifest.runtimeJsVersion, packageJson.version);
  assert.deepEqual(manifest.tap, {
    minimumSupportedVersion: 1,
    maximumSupportedVersion: 5,
  });
  assert.equal(manifest.componentAbiVersion, "0.4.0");
  assert.equal(manifest.quickjsAdapter, "rquickjs-0.12/quickjs-ng");
  assert.deepEqual(manifest.webApi, {
    profile: "tysel-server-web-subset",
    compatibilitySchemaVersion: 1,
  });
  assert.match(engineRust, /runtime-js\/compatibility\.json/);
});

test("Web API compatibility inventory is explicit and machine-readable", () => {
  const inventory = JSON.parse(
    readFileSync(new URL("../web-api/compatibility.json", import.meta.url), "utf8"),
  );
  assert.equal(inventory.schemaVersion, 1);
  assert.equal(inventory.profile, "tysel-server-web-subset");
  assert.equal(inventory.stability, "stable");
  assert.ok(inventory.apis.length >= 9);
  assert.deepEqual(
    [...new Set(inventory.apis.map((api) => api.name))],
    inventory.apis.map((api) => api.name),
  );
  for (const api of inventory.apis) {
    assert.match(api.status, /^(supported|partial|unsupported)$/);
    assert.ok(Array.isArray(api.supported));
    assert.ok(Array.isArray(api.unsupported));
    if (api.status === "partial") assert.ok(api.unsupported.length > 0);
  }
});

test("@tysel/types is a standalone public contract for the runtime surface", () => {
  const publicTypes = readFileSync(
    new URL("../../packages/tysel-types/src/index.ts", import.meta.url),
    "utf8",
  );
  const packageJson = JSON.parse(
    readFileSync(
      new URL("../../packages/tysel-types/package.json", import.meta.url),
      "utf8",
    ),
  );
  const capabilities = readFileSync(
    new URL("../capability-client/index.ts", import.meta.url),
    "utf8",
  );
  const webApi = readFileSync(new URL("../web-api/index.ts", import.meta.url), "utf8");

  assert.equal(packageJson.private, undefined);
  assert.equal(packageJson.dependencies, undefined);
  assert.equal(packageJson.types, "./dist/index.d.ts");
  assert.deepEqual(packageJson.files, ["dist", "LICENSE", "README.md"]);
  assert.doesNotMatch(publicTypes, /@tysel\/runtime-js/);
  assert.doesNotMatch(publicTypes, /\b_[A-Za-z][A-Za-z0-9]*\s*\(/);
  assert.match(publicTypes, /export interface TyselRuntime/);
  assert.match(publicTypes, /export interface SqlClient/);
  assert.match(publicTypes, /export interface DurableContext/);
  assert.match(publicTypes, /export interface LlmGenerateOptions/);
  assert.match(publicTypes, /interface WebSocket/);
  assert.match(capabilities, /export interface TyselRuntime/);
  assert.match(webApi, /export interface TyselWebApiGlobals/);
});
