[package]
name = "tysel-engine-qjs"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true
description = "QuickJS-ng execution engine (v0.x compatibility engine)."

[lints]
workspace = true

[dependencies]
bytes.workspace = true
http-body-util.workspace = true
hyper.workspace = true
hyper-util.workspace = true
native-tls.workspace = true
rquickjs.workspace = true
tokio.workspace = true
tokio-native-tls.workspace = true
tysel-engine.workspace = true

[dev-dependencies]
tysel-build.workspace = true
