[package]
name = "tysel-cap-llm"
version.workspace = true
publish = false
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true
description = "Official LLM capability."

[lints]
workspace = true

[dependencies]
bytes.workspace = true
http-body-util.workspace = true
hyper.workspace = true
hyper-util.workspace = true
native-tls.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-native-tls.workspace = true
