[package]
name = "tysel-cap-sqlite"
version.workspace = true
publish = false
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true
description = "Official SQLite capability."

[lints]
workspace = true

[dependencies]
rusqlite = { version = "0.32", features = ["bundled"] }
serde_json.workspace = true
tysel-engine.workspace = true
