// Generated by scripts/build-runtime.mjs. Do not edit.
(() => {

// source: durable/source/helpers.part.js
  let active = false;
  let retryIndex = 0;

  function lookup(kind, key) {
    return JSON.parse(tysel._durableLookup(kind, key));
  }

  function encode(value) {
    const encoded = JSON.stringify(value);
    if (encoded === undefined) {
      throw new TypeError("durable values must be JSON serializable");
    }
    return encoded;
  }

  function enter() {
    if (active) {
      throw new Error("durable boundaries must be awaited sequentially");
    }
    active = true;
  }

  function durationMs(value) {
    if (typeof value === "number") {
      if (!Number.isFinite(value) || value < 0) throw new TypeError("invalid durable duration");
      return Math.floor(value);
    }
    const match = /^\s*(\d+(?:\.\d+)?)\s*(ms|s|m|h|d)\s*$/.exec(String(value));
    if (!match) throw new TypeError("invalid durable duration");
    const scales = { ms: 1, s: 1000, m: 60000, h: 3600000, d: 86400000 };
    const millis = Number(match[1]) * scales[match[2]];
    if (!Number.isSafeInteger(Math.floor(millis))) throw new TypeError("durable duration is too large");
    return Math.floor(millis);
  }

  function retryPolicy(value) {
    if (value === null || typeof value !== "object" || Array.isArray(value)) {
      throw new TypeError("durable retry policy must be an object");
    }
    const maxAttempts = value.maxAttempts === undefined ? 3 : Number(value.maxAttempts);
    if (!Number.isInteger(maxAttempts) || maxAttempts < 1 || maxAttempts > 100) {
      throw new TypeError("durable retry maxAttempts must be an integer from 1 to 100");
    }
    const delayMs = value.delay === undefined ? 0 : durationMs(value.delay);
    const factor = value.factor === undefined ? 2 : Number(value.factor);
    if (!Number.isFinite(factor) || factor < 1 || factor > 100) {
      throw new TypeError("durable retry factor must be from 1 to 100");
    }
    const maxDelayMs = value.maxDelay === undefined ? null : durationMs(value.maxDelay);
    return { maxAttempts, delayMs, factor, maxDelayMs };
  }

  function retryDelayMs(policy, attempt) {
    const scaled = Math.floor(policy.delayMs * Math.pow(policy.factor, attempt - 1));
    const millis = policy.maxDelayMs === null ? scaled : Math.min(scaled, policy.maxDelayMs);
    if (!Number.isSafeInteger(millis)) {
      throw new TypeError("durable retry delay is too large");
    }
    return millis;
  }

  function retryFailure(error) {
    let name = "Error";
    let message = "retry callback failed";
    try {
      if (error && typeof error.name === "string") name = error.name;
      message = error && typeof error.message === "string" ? error.message : String(error);
    } catch (_) {}
    return { name: name.slice(0, 256), message: message.slice(0, 4096) };
  }

  function throwRetryFailure(failure) {
    if (!failure || typeof failure.name !== "string" || typeof failure.message !== "string") {
      throw new Error("invalid durable retry history");
    }
    const error = new Error(failure.message);
    error.name = failure.name;
    throw error;
  }

  function retryLookupOrRecord(key, payload) {
    enter();
    try {
      const replay = lookup("retry", key);
      if (replay.found) return replay.payload;
      if (payload !== undefined) {
        tysel._durableRecord("retry", key, encode(payload), Date.now());
      }
      return undefined;
    } finally {
      active = false;
    }
  }
  function findRetryOutcome(key) {
    enter();
    try {
      return JSON.parse(tysel._durableFindRetryOutcome(key));
    } finally {
      active = false;
    }
  }

  function applyRetryOutcome(outcome) {
    if (!outcome || typeof outcome.ok !== "boolean") {
      throw new Error("invalid durable retry outcome");
    }
    if (outcome.ok) return outcome.value;
    throwRetryFailure(outcome.failure);
  }

  async function boundary(kind, name, fn) {
    if (typeof fn !== "function") throw new TypeError("durable boundary requires a function");
    enter();
    try {
      const replay = lookup(kind, String(name));
      if (replay.found) return replay.payload;
      const value = await fn();
      tysel._durableRecord(kind, String(name), encode(value), Date.now());
      return value;
    } finally {
      active = false;
    }
  }

// source: durable/source/api.part.js
  const durable = {
    step(name, fn) {
      return boundary("step", name, fn);
    },
    effect(name, fn) {
      return boundary("effect", name, fn);
    },
    now() {
      enter();
      try {
        const replay = lookup("now", "now");
        if (replay.found) return new Date(replay.payload);
        const value = Date.now();
        tysel._durableRecord("now", "now", encode(value), value);
        return new Date(value);
      } finally {
        active = false;
      }
    },
    random() {
      enter();
      try {
        const replay = lookup("random", "random");
        if (replay.found) return replay.payload;
        const value = Math.random();
        tysel._durableRecord("random", "random", encode(value), Date.now());
        return value;
      } finally {
        active = false;
      }
    },
    async sleep(duration) {
      const millis = durationMs(duration);
      const key = "sleep:" + millis;
      enter();
      try {
        const replay = lookup("sleep", key);
        if (replay.found) {
          tysel._durableCompleteSleep();
          return;
        }
        const now = Date.now();
        const wakeAt = now + millis;
        if (!Number.isSafeInteger(wakeAt)) throw new TypeError("durable wakeup is too large");
        tysel._durableRecordSleep(key, encode({ durationMs: millis }), now, wakeAt);
        await tysel.sleep(millis);
        tysel._durableCompleteSleep();
      } finally {
        active = false;
      }
    },
    async waitForSignal(name) {
      const key = String(name);
      if (!key) throw new TypeError("durable signal name cannot be empty");
      enter();
      try {
        const replay = lookup("signal", key);
        if (replay.found) return replay.payload;
        const signal = JSON.parse(tysel._durablePollSignal(key));
        if (signal.found) return signal.payload;
        await new Promise(() => {});
      } finally {
        active = false;
      }
    },
    async retry(policyValue, fn) {
      if (typeof fn !== "function") throw new TypeError("durable retry requires a function");
      const policy = retryPolicy(policyValue);
      const retryId = retryIndex++;
      const scope = [
        "retry",
        retryId,
        policy.maxAttempts,
        policy.delayMs,
        policy.factor,
        policy.maxDelayMs === null ? "none" : policy.maxDelayMs,
      ].join(":");
      for (let attempt = 1; attempt <= policy.maxAttempts; attempt++) {
        retryLookupOrRecord(scope + ":start:" + attempt, { attempt });
        const outcomeKey = scope + ":outcome:" + attempt;
        const replayedOutcome = findRetryOutcome(outcomeKey);
        if (replayedOutcome.found) {
          const outcome = replayedOutcome.payload;
          if (outcome && outcome.ok === true) return applyRetryOutcome(outcome);
          if (attempt === policy.maxAttempts) return applyRetryOutcome(outcome);
          const delayMs = retryDelayMs(policy, attempt);
          if (delayMs > 0) await durable.sleep(delayMs);
          continue;
        }
        let failed = false;
        let failure;
        let value;
        try {
          value = await fn(attempt);
        } catch (error) {
          failed = true;
          failure = retryFailure(error);
        }
        const outcome = failed ? { ok: false, failure } : { ok: true, value };
        retryLookupOrRecord(outcomeKey, outcome);
        if (!failed) return applyRetryOutcome(outcome);
        if (attempt === policy.maxAttempts) throwRetryFailure(failure);
        const delayMs = retryDelayMs(policy, attempt);
        if (delayMs > 0) await durable.sleep(delayMs);
      }
      throw new Error("durable retry exhausted unexpectedly");
    },
  };
  globalThis.tysel.durable = durable;
})();
