[package]
name = "tysel-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true
description = "Tysel command-line interface"

[lints]
workspace = true

[[bin]]
name = "tysel"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
tysel-manifest.workspace = true
tysel-build.workspace = true

[dev-dependencies]
tysel-package.workspace = true
