use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result, anyhow};
use tysel_manifest::{Manifest, parse_postgres_grant};

use crate::project::ProjectContext;

const GENERATED_HEADER: &str = "// Generated by `tysel types`. Do not edit.\n";

pub fn run(context: &ProjectContext, output: Option<&Path>, check: bool) -> Result<()> {
    let path = resolve_output_path(&context.root, output)?;
    let rendered = render(&context.manifest)?;

    if fs::symlink_metadata(&path).is_ok_and(|metadata| metadata.file_type().is_symlink()) {
        return Err(anyhow!("refusing to use symlinked generated types {}", path.display()));
    }
    if check {
        let current = fs::read_to_string(&path)
            .with_context(|| format!("read generated types {}", path.display()))?;
        if current != rendered {
            return Err(anyhow!("generated types are out of date: run `tysel types`"));
        }
        println!("types ok {}", display_path(&path, &context.root).display());
        return Ok(());
    }

    if path.is_file() {
        let current = fs::read_to_string(&path)
            .with_context(|| format!("read existing generated types {}", path.display()))?;
        if !current.starts_with(GENERATED_HEADER) {
            return Err(anyhow!(
                "refusing to replace non-generated file {}; choose --output",
                path.display()
            ));
        }
    }
    let parent = path.parent().unwrap_or(&context.root);
    fs::create_dir_all(parent)
        .with_context(|| format!("create generated types directory {}", parent.display()))?;
    fs::write(&path, rendered)
        .with_context(|| format!("write generated types {}", path.display()))?;
    println!("wrote {}", display_path(&path, &context.root).display());
    Ok(())
}

fn resolve_output_path(root: &Path, output: Option<&Path>) -> Result<PathBuf> {
    let output = output.unwrap_or_else(|| Path::new("tysel-env.d.ts"));
    let mut relative = PathBuf::new();
    for component in output.components() {
        match component {
            std::path::Component::Normal(value) => relative.push(value),
            std::path::Component::CurDir => {}
            std::path::Component::ParentDir
            | std::path::Component::RootDir
            | std::path::Component::Prefix(_) => {
                return Err(anyhow!(
                    "generated types output must be a project-relative path without '..'"
                ));
            }
        }
    }
    if relative.as_os_str().is_empty() {
        return Err(anyhow!("generated types output must name a file"));
    }

    let path = root.join(relative);
    ensure_safe_destination(root, &path)?;
    Ok(path)
}

fn ensure_safe_destination(root: &Path, destination: &Path) -> Result<()> {
    let canonical_root = fs::canonicalize(root)
        .with_context(|| format!("resolve project root {}", root.display()))?;
    let mut existing_parent = destination.parent().unwrap_or(root);
    while !existing_parent.exists() {
        existing_parent = existing_parent.parent().ok_or_else(|| {
            anyhow!("cannot resolve parent directory for {}", destination.display())
        })?;
    }
    let canonical_parent = fs::canonicalize(existing_parent)
        .with_context(|| format!("resolve destination parent {}", existing_parent.display()))?;
    if !canonical_parent.starts_with(&canonical_root) {
        return Err(anyhow!(
            "refusing to create {} through a path outside project root {}",
            destination.display(),
            canonical_root.display()
        ));
    }
    Ok(())
}

pub fn render(manifest: &Manifest) -> Result<String> {
    let service = manifest.app.profile == "service";
    let mut capabilities = Vec::new();
    let mut imports = vec!["TyselRuntimeWith"];
    let mut overrides: Vec<(&str, String)> = Vec::new();

    if service && manifest.durable.store == "sqlite" {
        capabilities.extend(["sqlite", "durable"]);
    }
    if service && !manifest.permissions.fetch.is_empty() {
        capabilities.push("httpGet");
    }
    if service && manifest.server.websocket {
        capabilities.push("acceptWebSocket");
    }
    if service && !manifest.permissions.postgres.is_empty() {
        let grant = parse_postgres_grant(&manifest.permissions.postgres[0])
            .map_err(|error| anyhow!(error))?;
        if grant.mode.as_deref() == Some("read-only") {
            imports.push("SqlClient");
            overrides.push(("postgres", "  readonly postgres: Pick<SqlClient, \"query\">;".into()));
        } else {
            capabilities.push("postgres");
        }
    }
    if service
        && (!manifest.permissions.fs_read.is_empty() || !manifest.permissions.fs_write.is_empty())
    {
        imports.push("FileSystemClient");
        let mut methods = Vec::new();
        if !manifest.permissions.fs_read.is_empty() {
            methods.push("\"read\"");
        }
        if !manifest.permissions.fs_write.is_empty() {
            methods.push("\"write\"");
        }
        overrides.push((
            "fs",
            format!("  readonly fs: Pick<FileSystemClient, {}>;", methods.join(" | ")),
        ));
    }
    if !manifest.permissions.secrets.is_empty() {
        imports.push("SecretClient");
        let names = manifest
            .permissions
            .secrets
            .iter()
            .map(|name| serde_json::to_string(name).expect("string serialization"))
            .collect::<Vec<_>>()
            .join(" | ");
        overrides.push(("secrets", format!("  readonly secrets: SecretClient<{names}>;")));
    }

    imports.sort_unstable();
    imports.dedup();
    capabilities.sort_unstable();
    capabilities.dedup();
    let selected = if capabilities.is_empty() {
        "never".to_owned()
    } else {
        capabilities.iter().map(|name| format!("\"{name}\"")).collect::<Vec<_>>().join(" | ")
    };

    let mut out = String::from(GENERATED_HEADER);
    out.push_str("import type { ");
    out.push_str(&imports.join(", "));
    out.push_str(" } from \"@tysel/types\";\n\n");
    if overrides.is_empty() {
        out.push_str(&format!("export type TyselEnv = TyselRuntimeWith<{selected}>;\n"));
    } else {
        let omitted =
            overrides.iter().map(|(name, _)| format!("\"{name}\"")).collect::<Vec<_>>().join(" | ");
        out.push_str(&format!(
            "type BaseRuntime = Omit<TyselRuntimeWith<{selected}>, {omitted}>;\n\n"
        ));
        out.push_str("export type TyselEnv = BaseRuntime & {\n");
        for (_, line) in overrides {
            out.push_str(&line);
            out.push('\n');
        }
        out.push_str("};\n");
    }
    Ok(out)
}

fn display_path(path: &Path, root: &Path) -> PathBuf {
    path.strip_prefix(root).unwrap_or(path).to_path_buf()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn manifest(profile: &str) -> Manifest {
        Manifest::parse(&format!(
            r#"
[app]
name = "typegen-test"
entry = "src/index.ts"
profile = "{profile}"
"#
        ))
        .unwrap()
    }

    #[test]
    fn generated_runtime_tracks_manifest_capabilities() {
        let mut manifest = manifest("service");
        manifest.permissions.fetch = vec!["api.example.com".into()];
        manifest.permissions.secrets = vec!["API_TOKEN".into()];
        manifest.permissions.postgres = vec!["main:read-only".into()];
        manifest.permissions.fs_read = vec!["./input".into()];
        manifest.server.websocket = true;

        let output = render(&manifest).unwrap();
        assert!(output.contains("\"acceptWebSocket\""));
        assert!(output.contains("\"durable\""));
        assert!(output.contains("\"httpGet\""));
        assert!(output.contains("\"sqlite\""));
        assert!(output.contains("Pick<SqlClient, \"query\">"));
        assert!(output.contains("Pick<FileSystemClient, \"read\">"));
        assert!(output.contains("SecretClient<\"API_TOKEN\">"));
    }

    #[test]
    fn isolated_profile_omits_direct_host_capabilities() {
        let mut manifest = manifest("isolated");
        manifest.permissions.postgres = vec!["main:read-write".into()];
        manifest.permissions.fs_write = vec!["./output".into()];

        let output = render(&manifest).unwrap();
        assert!(output.contains("TyselRuntimeWith<never>"));
        assert!(!output.contains("FileSystemClient"));
        assert!(!output.contains("\"postgres\""));
    }

    #[test]
    fn output_must_be_project_relative() {
        let root = std::env::temp_dir();
        assert!(resolve_output_path(&root, Some(Path::new("../outside.d.ts"))).is_err());
        assert!(resolve_output_path(&root, Some(Path::new("/outside.d.ts"))).is_err());
    }

    #[cfg(unix)]
    #[test]
    fn output_rejects_a_parent_symlink_outside_the_project() {
        use std::os::unix::fs::symlink;

        let base = std::env::temp_dir().join(format!(
            "tysel-typegen-path-{}-{}",
            std::process::id(),
            std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).unwrap().as_nanos()
        ));
        let root = base.join("project");
        let outside = base.join("outside");
        fs::create_dir_all(&root).unwrap();
        fs::create_dir_all(&outside).unwrap();
        symlink(&outside, root.join("generated")).unwrap();

        let result = resolve_output_path(&root, Some(Path::new("generated/tysel-env.d.ts")));
        assert!(result.unwrap_err().to_string().contains("outside project root"));

        fs::remove_dir_all(base).unwrap();
    }
}
